// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ClientDatanodeProtocol.proto

package hadoop_hdfs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	. "github.com/jaguarx/go-hadoop-proto.v3/hadoop/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// block - block for which visible length is requested
type GetReplicaVisibleLengthRequestProto struct {
	Block                *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetReplicaVisibleLengthRequestProto) Reset()         { *m = GetReplicaVisibleLengthRequestProto{} }
func (m *GetReplicaVisibleLengthRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetReplicaVisibleLengthRequestProto) ProtoMessage()    {}
func (*GetReplicaVisibleLengthRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{0}
}

func (m *GetReplicaVisibleLengthRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplicaVisibleLengthRequestProto.Unmarshal(m, b)
}
func (m *GetReplicaVisibleLengthRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplicaVisibleLengthRequestProto.Marshal(b, m, deterministic)
}
func (m *GetReplicaVisibleLengthRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplicaVisibleLengthRequestProto.Merge(m, src)
}
func (m *GetReplicaVisibleLengthRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetReplicaVisibleLengthRequestProto.Size(m)
}
func (m *GetReplicaVisibleLengthRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplicaVisibleLengthRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplicaVisibleLengthRequestProto proto.InternalMessageInfo

func (m *GetReplicaVisibleLengthRequestProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

//*
// length - visible length of the block
type GetReplicaVisibleLengthResponseProto struct {
	Length               *uint64  `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReplicaVisibleLengthResponseProto) Reset()         { *m = GetReplicaVisibleLengthResponseProto{} }
func (m *GetReplicaVisibleLengthResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetReplicaVisibleLengthResponseProto) ProtoMessage()    {}
func (*GetReplicaVisibleLengthResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{1}
}

func (m *GetReplicaVisibleLengthResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplicaVisibleLengthResponseProto.Unmarshal(m, b)
}
func (m *GetReplicaVisibleLengthResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplicaVisibleLengthResponseProto.Marshal(b, m, deterministic)
}
func (m *GetReplicaVisibleLengthResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplicaVisibleLengthResponseProto.Merge(m, src)
}
func (m *GetReplicaVisibleLengthResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetReplicaVisibleLengthResponseProto.Size(m)
}
func (m *GetReplicaVisibleLengthResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplicaVisibleLengthResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplicaVisibleLengthResponseProto proto.InternalMessageInfo

func (m *GetReplicaVisibleLengthResponseProto) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

//*
// void request
type RefreshNamenodesRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshNamenodesRequestProto) Reset()         { *m = RefreshNamenodesRequestProto{} }
func (m *RefreshNamenodesRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshNamenodesRequestProto) ProtoMessage()    {}
func (*RefreshNamenodesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{2}
}

func (m *RefreshNamenodesRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshNamenodesRequestProto.Unmarshal(m, b)
}
func (m *RefreshNamenodesRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshNamenodesRequestProto.Marshal(b, m, deterministic)
}
func (m *RefreshNamenodesRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshNamenodesRequestProto.Merge(m, src)
}
func (m *RefreshNamenodesRequestProto) XXX_Size() int {
	return xxx_messageInfo_RefreshNamenodesRequestProto.Size(m)
}
func (m *RefreshNamenodesRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshNamenodesRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshNamenodesRequestProto proto.InternalMessageInfo

//*
// void response
type RefreshNamenodesResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshNamenodesResponseProto) Reset()         { *m = RefreshNamenodesResponseProto{} }
func (m *RefreshNamenodesResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshNamenodesResponseProto) ProtoMessage()    {}
func (*RefreshNamenodesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{3}
}

func (m *RefreshNamenodesResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshNamenodesResponseProto.Unmarshal(m, b)
}
func (m *RefreshNamenodesResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshNamenodesResponseProto.Marshal(b, m, deterministic)
}
func (m *RefreshNamenodesResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshNamenodesResponseProto.Merge(m, src)
}
func (m *RefreshNamenodesResponseProto) XXX_Size() int {
	return xxx_messageInfo_RefreshNamenodesResponseProto.Size(m)
}
func (m *RefreshNamenodesResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshNamenodesResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshNamenodesResponseProto proto.InternalMessageInfo

//*
// blockPool - block pool to be deleted
// force - if false, delete the block pool only if it is empty.
//         if true, delete the block pool even if it has blocks.
type DeleteBlockPoolRequestProto struct {
	BlockPool            *string  `protobuf:"bytes,1,req,name=blockPool" json:"blockPool,omitempty"`
	Force                *bool    `protobuf:"varint,2,req,name=force" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlockPoolRequestProto) Reset()         { *m = DeleteBlockPoolRequestProto{} }
func (m *DeleteBlockPoolRequestProto) String() string { return proto.CompactTextString(m) }
func (*DeleteBlockPoolRequestProto) ProtoMessage()    {}
func (*DeleteBlockPoolRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{4}
}

func (m *DeleteBlockPoolRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlockPoolRequestProto.Unmarshal(m, b)
}
func (m *DeleteBlockPoolRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlockPoolRequestProto.Marshal(b, m, deterministic)
}
func (m *DeleteBlockPoolRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlockPoolRequestProto.Merge(m, src)
}
func (m *DeleteBlockPoolRequestProto) XXX_Size() int {
	return xxx_messageInfo_DeleteBlockPoolRequestProto.Size(m)
}
func (m *DeleteBlockPoolRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlockPoolRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlockPoolRequestProto proto.InternalMessageInfo

func (m *DeleteBlockPoolRequestProto) GetBlockPool() string {
	if m != nil && m.BlockPool != nil {
		return *m.BlockPool
	}
	return ""
}

func (m *DeleteBlockPoolRequestProto) GetForce() bool {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return false
}

//*
// void response
type DeleteBlockPoolResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlockPoolResponseProto) Reset()         { *m = DeleteBlockPoolResponseProto{} }
func (m *DeleteBlockPoolResponseProto) String() string { return proto.CompactTextString(m) }
func (*DeleteBlockPoolResponseProto) ProtoMessage()    {}
func (*DeleteBlockPoolResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{5}
}

func (m *DeleteBlockPoolResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlockPoolResponseProto.Unmarshal(m, b)
}
func (m *DeleteBlockPoolResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlockPoolResponseProto.Marshal(b, m, deterministic)
}
func (m *DeleteBlockPoolResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlockPoolResponseProto.Merge(m, src)
}
func (m *DeleteBlockPoolResponseProto) XXX_Size() int {
	return xxx_messageInfo_DeleteBlockPoolResponseProto.Size(m)
}
func (m *DeleteBlockPoolResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlockPoolResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlockPoolResponseProto proto.InternalMessageInfo

//*
// Gets the file information where block and its metadata is stored
// block - block for which path information is being requested
// token - block token
//
// This message is deprecated in favor of file descriptor passing.
type GetBlockLocalPathInfoRequestProto struct {
	Block                *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	Token                *TokenProto         `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetBlockLocalPathInfoRequestProto) Reset()         { *m = GetBlockLocalPathInfoRequestProto{} }
func (m *GetBlockLocalPathInfoRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetBlockLocalPathInfoRequestProto) ProtoMessage()    {}
func (*GetBlockLocalPathInfoRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{6}
}

func (m *GetBlockLocalPathInfoRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockLocalPathInfoRequestProto.Unmarshal(m, b)
}
func (m *GetBlockLocalPathInfoRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockLocalPathInfoRequestProto.Marshal(b, m, deterministic)
}
func (m *GetBlockLocalPathInfoRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockLocalPathInfoRequestProto.Merge(m, src)
}
func (m *GetBlockLocalPathInfoRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetBlockLocalPathInfoRequestProto.Size(m)
}
func (m *GetBlockLocalPathInfoRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockLocalPathInfoRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockLocalPathInfoRequestProto proto.InternalMessageInfo

func (m *GetBlockLocalPathInfoRequestProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *GetBlockLocalPathInfoRequestProto) GetToken() *TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

//*
// block - block for which file path information is being returned
// localPath - file path where the block data is stored
// localMetaPath - file path where the block meta data is stored
//
// This message is deprecated in favor of file descriptor passing.
type GetBlockLocalPathInfoResponseProto struct {
	Block                *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	LocalPath            *string             `protobuf:"bytes,2,req,name=localPath" json:"localPath,omitempty"`
	LocalMetaPath        *string             `protobuf:"bytes,3,req,name=localMetaPath" json:"localMetaPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetBlockLocalPathInfoResponseProto) Reset()         { *m = GetBlockLocalPathInfoResponseProto{} }
func (m *GetBlockLocalPathInfoResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetBlockLocalPathInfoResponseProto) ProtoMessage()    {}
func (*GetBlockLocalPathInfoResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{7}
}

func (m *GetBlockLocalPathInfoResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockLocalPathInfoResponseProto.Unmarshal(m, b)
}
func (m *GetBlockLocalPathInfoResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockLocalPathInfoResponseProto.Marshal(b, m, deterministic)
}
func (m *GetBlockLocalPathInfoResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockLocalPathInfoResponseProto.Merge(m, src)
}
func (m *GetBlockLocalPathInfoResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetBlockLocalPathInfoResponseProto.Size(m)
}
func (m *GetBlockLocalPathInfoResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockLocalPathInfoResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockLocalPathInfoResponseProto proto.InternalMessageInfo

func (m *GetBlockLocalPathInfoResponseProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *GetBlockLocalPathInfoResponseProto) GetLocalPath() string {
	if m != nil && m.LocalPath != nil {
		return *m.LocalPath
	}
	return ""
}

func (m *GetBlockLocalPathInfoResponseProto) GetLocalMetaPath() string {
	if m != nil && m.LocalMetaPath != nil {
		return *m.LocalMetaPath
	}
	return ""
}

//*
// forUpgrade - if true, clients are advised to wait for restart and quick
//              upgrade restart is instrumented. Otherwise, datanode does
//              the regular shutdown.
type ShutdownDatanodeRequestProto struct {
	ForUpgrade           *bool    `protobuf:"varint,1,req,name=forUpgrade" json:"forUpgrade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownDatanodeRequestProto) Reset()         { *m = ShutdownDatanodeRequestProto{} }
func (m *ShutdownDatanodeRequestProto) String() string { return proto.CompactTextString(m) }
func (*ShutdownDatanodeRequestProto) ProtoMessage()    {}
func (*ShutdownDatanodeRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{8}
}

func (m *ShutdownDatanodeRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownDatanodeRequestProto.Unmarshal(m, b)
}
func (m *ShutdownDatanodeRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownDatanodeRequestProto.Marshal(b, m, deterministic)
}
func (m *ShutdownDatanodeRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownDatanodeRequestProto.Merge(m, src)
}
func (m *ShutdownDatanodeRequestProto) XXX_Size() int {
	return xxx_messageInfo_ShutdownDatanodeRequestProto.Size(m)
}
func (m *ShutdownDatanodeRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownDatanodeRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownDatanodeRequestProto proto.InternalMessageInfo

func (m *ShutdownDatanodeRequestProto) GetForUpgrade() bool {
	if m != nil && m.ForUpgrade != nil {
		return *m.ForUpgrade
	}
	return false
}

type ShutdownDatanodeResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownDatanodeResponseProto) Reset()         { *m = ShutdownDatanodeResponseProto{} }
func (m *ShutdownDatanodeResponseProto) String() string { return proto.CompactTextString(m) }
func (*ShutdownDatanodeResponseProto) ProtoMessage()    {}
func (*ShutdownDatanodeResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{9}
}

func (m *ShutdownDatanodeResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownDatanodeResponseProto.Unmarshal(m, b)
}
func (m *ShutdownDatanodeResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownDatanodeResponseProto.Marshal(b, m, deterministic)
}
func (m *ShutdownDatanodeResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownDatanodeResponseProto.Merge(m, src)
}
func (m *ShutdownDatanodeResponseProto) XXX_Size() int {
	return xxx_messageInfo_ShutdownDatanodeResponseProto.Size(m)
}
func (m *ShutdownDatanodeResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownDatanodeResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownDatanodeResponseProto proto.InternalMessageInfo

//* Tell datanode to evict active clients that are writing
type EvictWritersRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvictWritersRequestProto) Reset()         { *m = EvictWritersRequestProto{} }
func (m *EvictWritersRequestProto) String() string { return proto.CompactTextString(m) }
func (*EvictWritersRequestProto) ProtoMessage()    {}
func (*EvictWritersRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{10}
}

func (m *EvictWritersRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvictWritersRequestProto.Unmarshal(m, b)
}
func (m *EvictWritersRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvictWritersRequestProto.Marshal(b, m, deterministic)
}
func (m *EvictWritersRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvictWritersRequestProto.Merge(m, src)
}
func (m *EvictWritersRequestProto) XXX_Size() int {
	return xxx_messageInfo_EvictWritersRequestProto.Size(m)
}
func (m *EvictWritersRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EvictWritersRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_EvictWritersRequestProto proto.InternalMessageInfo

type EvictWritersResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvictWritersResponseProto) Reset()         { *m = EvictWritersResponseProto{} }
func (m *EvictWritersResponseProto) String() string { return proto.CompactTextString(m) }
func (*EvictWritersResponseProto) ProtoMessage()    {}
func (*EvictWritersResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{11}
}

func (m *EvictWritersResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvictWritersResponseProto.Unmarshal(m, b)
}
func (m *EvictWritersResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvictWritersResponseProto.Marshal(b, m, deterministic)
}
func (m *EvictWritersResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvictWritersResponseProto.Merge(m, src)
}
func (m *EvictWritersResponseProto) XXX_Size() int {
	return xxx_messageInfo_EvictWritersResponseProto.Size(m)
}
func (m *EvictWritersResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EvictWritersResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_EvictWritersResponseProto proto.InternalMessageInfo

//*
// Ping datanode for liveness and quick info
type GetDatanodeInfoRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatanodeInfoRequestProto) Reset()         { *m = GetDatanodeInfoRequestProto{} }
func (m *GetDatanodeInfoRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetDatanodeInfoRequestProto) ProtoMessage()    {}
func (*GetDatanodeInfoRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{12}
}

func (m *GetDatanodeInfoRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatanodeInfoRequestProto.Unmarshal(m, b)
}
func (m *GetDatanodeInfoRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatanodeInfoRequestProto.Marshal(b, m, deterministic)
}
func (m *GetDatanodeInfoRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatanodeInfoRequestProto.Merge(m, src)
}
func (m *GetDatanodeInfoRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetDatanodeInfoRequestProto.Size(m)
}
func (m *GetDatanodeInfoRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatanodeInfoRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatanodeInfoRequestProto proto.InternalMessageInfo

type GetDatanodeInfoResponseProto struct {
	LocalInfo            *DatanodeLocalInfoProto `protobuf:"bytes,1,req,name=localInfo" json:"localInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetDatanodeInfoResponseProto) Reset()         { *m = GetDatanodeInfoResponseProto{} }
func (m *GetDatanodeInfoResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetDatanodeInfoResponseProto) ProtoMessage()    {}
func (*GetDatanodeInfoResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{13}
}

func (m *GetDatanodeInfoResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatanodeInfoResponseProto.Unmarshal(m, b)
}
func (m *GetDatanodeInfoResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatanodeInfoResponseProto.Marshal(b, m, deterministic)
}
func (m *GetDatanodeInfoResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatanodeInfoResponseProto.Merge(m, src)
}
func (m *GetDatanodeInfoResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetDatanodeInfoResponseProto.Size(m)
}
func (m *GetDatanodeInfoResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatanodeInfoResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatanodeInfoResponseProto proto.InternalMessageInfo

func (m *GetDatanodeInfoResponseProto) GetLocalInfo() *DatanodeLocalInfoProto {
	if m != nil {
		return m.LocalInfo
	}
	return nil
}

type GetVolumeReportRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumeReportRequestProto) Reset()         { *m = GetVolumeReportRequestProto{} }
func (m *GetVolumeReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetVolumeReportRequestProto) ProtoMessage()    {}
func (*GetVolumeReportRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{14}
}

func (m *GetVolumeReportRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeReportRequestProto.Unmarshal(m, b)
}
func (m *GetVolumeReportRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeReportRequestProto.Marshal(b, m, deterministic)
}
func (m *GetVolumeReportRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeReportRequestProto.Merge(m, src)
}
func (m *GetVolumeReportRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetVolumeReportRequestProto.Size(m)
}
func (m *GetVolumeReportRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeReportRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeReportRequestProto proto.InternalMessageInfo

type GetVolumeReportResponseProto struct {
	VolumeInfo           []*DatanodeVolumeInfoProto `protobuf:"bytes,1,rep,name=volumeInfo" json:"volumeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetVolumeReportResponseProto) Reset()         { *m = GetVolumeReportResponseProto{} }
func (m *GetVolumeReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetVolumeReportResponseProto) ProtoMessage()    {}
func (*GetVolumeReportResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{15}
}

func (m *GetVolumeReportResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeReportResponseProto.Unmarshal(m, b)
}
func (m *GetVolumeReportResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeReportResponseProto.Marshal(b, m, deterministic)
}
func (m *GetVolumeReportResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeReportResponseProto.Merge(m, src)
}
func (m *GetVolumeReportResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetVolumeReportResponseProto.Size(m)
}
func (m *GetVolumeReportResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeReportResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeReportResponseProto proto.InternalMessageInfo

func (m *GetVolumeReportResponseProto) GetVolumeInfo() []*DatanodeVolumeInfoProto {
	if m != nil {
		return m.VolumeInfo
	}
	return nil
}

type TriggerBlockReportRequestProto struct {
	Incremental          *bool    `protobuf:"varint,1,req,name=incremental" json:"incremental,omitempty"`
	NnAddress            *string  `protobuf:"bytes,2,opt,name=nnAddress" json:"nnAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerBlockReportRequestProto) Reset()         { *m = TriggerBlockReportRequestProto{} }
func (m *TriggerBlockReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*TriggerBlockReportRequestProto) ProtoMessage()    {}
func (*TriggerBlockReportRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{16}
}

func (m *TriggerBlockReportRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerBlockReportRequestProto.Unmarshal(m, b)
}
func (m *TriggerBlockReportRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerBlockReportRequestProto.Marshal(b, m, deterministic)
}
func (m *TriggerBlockReportRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerBlockReportRequestProto.Merge(m, src)
}
func (m *TriggerBlockReportRequestProto) XXX_Size() int {
	return xxx_messageInfo_TriggerBlockReportRequestProto.Size(m)
}
func (m *TriggerBlockReportRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerBlockReportRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerBlockReportRequestProto proto.InternalMessageInfo

func (m *TriggerBlockReportRequestProto) GetIncremental() bool {
	if m != nil && m.Incremental != nil {
		return *m.Incremental
	}
	return false
}

func (m *TriggerBlockReportRequestProto) GetNnAddress() string {
	if m != nil && m.NnAddress != nil {
		return *m.NnAddress
	}
	return ""
}

type TriggerBlockReportResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerBlockReportResponseProto) Reset()         { *m = TriggerBlockReportResponseProto{} }
func (m *TriggerBlockReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*TriggerBlockReportResponseProto) ProtoMessage()    {}
func (*TriggerBlockReportResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{17}
}

func (m *TriggerBlockReportResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerBlockReportResponseProto.Unmarshal(m, b)
}
func (m *TriggerBlockReportResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerBlockReportResponseProto.Marshal(b, m, deterministic)
}
func (m *TriggerBlockReportResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerBlockReportResponseProto.Merge(m, src)
}
func (m *TriggerBlockReportResponseProto) XXX_Size() int {
	return xxx_messageInfo_TriggerBlockReportResponseProto.Size(m)
}
func (m *TriggerBlockReportResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerBlockReportResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerBlockReportResponseProto proto.InternalMessageInfo

type GetBalancerBandwidthRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalancerBandwidthRequestProto) Reset()         { *m = GetBalancerBandwidthRequestProto{} }
func (m *GetBalancerBandwidthRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetBalancerBandwidthRequestProto) ProtoMessage()    {}
func (*GetBalancerBandwidthRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{18}
}

func (m *GetBalancerBandwidthRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalancerBandwidthRequestProto.Unmarshal(m, b)
}
func (m *GetBalancerBandwidthRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalancerBandwidthRequestProto.Marshal(b, m, deterministic)
}
func (m *GetBalancerBandwidthRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalancerBandwidthRequestProto.Merge(m, src)
}
func (m *GetBalancerBandwidthRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetBalancerBandwidthRequestProto.Size(m)
}
func (m *GetBalancerBandwidthRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalancerBandwidthRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalancerBandwidthRequestProto proto.InternalMessageInfo

//*
// bandwidth - balancer bandwidth value of the datanode.
type GetBalancerBandwidthResponseProto struct {
	Bandwidth            *uint64  `protobuf:"varint,1,req,name=bandwidth" json:"bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalancerBandwidthResponseProto) Reset()         { *m = GetBalancerBandwidthResponseProto{} }
func (m *GetBalancerBandwidthResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetBalancerBandwidthResponseProto) ProtoMessage()    {}
func (*GetBalancerBandwidthResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{19}
}

func (m *GetBalancerBandwidthResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalancerBandwidthResponseProto.Unmarshal(m, b)
}
func (m *GetBalancerBandwidthResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalancerBandwidthResponseProto.Marshal(b, m, deterministic)
}
func (m *GetBalancerBandwidthResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalancerBandwidthResponseProto.Merge(m, src)
}
func (m *GetBalancerBandwidthResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetBalancerBandwidthResponseProto.Size(m)
}
func (m *GetBalancerBandwidthResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalancerBandwidthResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalancerBandwidthResponseProto proto.InternalMessageInfo

func (m *GetBalancerBandwidthResponseProto) GetBandwidth() uint64 {
	if m != nil && m.Bandwidth != nil {
		return *m.Bandwidth
	}
	return 0
}

//*
// This message allows a client to submit a disk
// balancer plan to a data node.
type SubmitDiskBalancerPlanRequestProto struct {
	PlanID               *string  `protobuf:"bytes,1,req,name=planID" json:"planID,omitempty"`
	Plan                 *string  `protobuf:"bytes,2,req,name=plan" json:"plan,omitempty"`
	PlanVersion          *uint64  `protobuf:"varint,3,opt,name=planVersion" json:"planVersion,omitempty"`
	IgnoreDateCheck      *bool    `protobuf:"varint,4,opt,name=ignoreDateCheck" json:"ignoreDateCheck,omitempty"`
	PlanFile             *string  `protobuf:"bytes,5,req,name=planFile" json:"planFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitDiskBalancerPlanRequestProto) Reset()         { *m = SubmitDiskBalancerPlanRequestProto{} }
func (m *SubmitDiskBalancerPlanRequestProto) String() string { return proto.CompactTextString(m) }
func (*SubmitDiskBalancerPlanRequestProto) ProtoMessage()    {}
func (*SubmitDiskBalancerPlanRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{20}
}

func (m *SubmitDiskBalancerPlanRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitDiskBalancerPlanRequestProto.Unmarshal(m, b)
}
func (m *SubmitDiskBalancerPlanRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitDiskBalancerPlanRequestProto.Marshal(b, m, deterministic)
}
func (m *SubmitDiskBalancerPlanRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitDiskBalancerPlanRequestProto.Merge(m, src)
}
func (m *SubmitDiskBalancerPlanRequestProto) XXX_Size() int {
	return xxx_messageInfo_SubmitDiskBalancerPlanRequestProto.Size(m)
}
func (m *SubmitDiskBalancerPlanRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitDiskBalancerPlanRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitDiskBalancerPlanRequestProto proto.InternalMessageInfo

func (m *SubmitDiskBalancerPlanRequestProto) GetPlanID() string {
	if m != nil && m.PlanID != nil {
		return *m.PlanID
	}
	return ""
}

func (m *SubmitDiskBalancerPlanRequestProto) GetPlan() string {
	if m != nil && m.Plan != nil {
		return *m.Plan
	}
	return ""
}

func (m *SubmitDiskBalancerPlanRequestProto) GetPlanVersion() uint64 {
	if m != nil && m.PlanVersion != nil {
		return *m.PlanVersion
	}
	return 0
}

func (m *SubmitDiskBalancerPlanRequestProto) GetIgnoreDateCheck() bool {
	if m != nil && m.IgnoreDateCheck != nil {
		return *m.IgnoreDateCheck
	}
	return false
}

func (m *SubmitDiskBalancerPlanRequestProto) GetPlanFile() string {
	if m != nil && m.PlanFile != nil {
		return *m.PlanFile
	}
	return ""
}

//*
// Response from the DataNode on Plan Submit request
type SubmitDiskBalancerPlanResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitDiskBalancerPlanResponseProto) Reset()         { *m = SubmitDiskBalancerPlanResponseProto{} }
func (m *SubmitDiskBalancerPlanResponseProto) String() string { return proto.CompactTextString(m) }
func (*SubmitDiskBalancerPlanResponseProto) ProtoMessage()    {}
func (*SubmitDiskBalancerPlanResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{21}
}

func (m *SubmitDiskBalancerPlanResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitDiskBalancerPlanResponseProto.Unmarshal(m, b)
}
func (m *SubmitDiskBalancerPlanResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitDiskBalancerPlanResponseProto.Marshal(b, m, deterministic)
}
func (m *SubmitDiskBalancerPlanResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitDiskBalancerPlanResponseProto.Merge(m, src)
}
func (m *SubmitDiskBalancerPlanResponseProto) XXX_Size() int {
	return xxx_messageInfo_SubmitDiskBalancerPlanResponseProto.Size(m)
}
func (m *SubmitDiskBalancerPlanResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitDiskBalancerPlanResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitDiskBalancerPlanResponseProto proto.InternalMessageInfo

//*
// This message describes a request to cancel an
// outstanding disk balancer plan
type CancelPlanRequestProto struct {
	PlanID               *string  `protobuf:"bytes,1,req,name=planID" json:"planID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPlanRequestProto) Reset()         { *m = CancelPlanRequestProto{} }
func (m *CancelPlanRequestProto) String() string { return proto.CompactTextString(m) }
func (*CancelPlanRequestProto) ProtoMessage()    {}
func (*CancelPlanRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{22}
}

func (m *CancelPlanRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPlanRequestProto.Unmarshal(m, b)
}
func (m *CancelPlanRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPlanRequestProto.Marshal(b, m, deterministic)
}
func (m *CancelPlanRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPlanRequestProto.Merge(m, src)
}
func (m *CancelPlanRequestProto) XXX_Size() int {
	return xxx_messageInfo_CancelPlanRequestProto.Size(m)
}
func (m *CancelPlanRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPlanRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPlanRequestProto proto.InternalMessageInfo

func (m *CancelPlanRequestProto) GetPlanID() string {
	if m != nil && m.PlanID != nil {
		return *m.PlanID
	}
	return ""
}

//*
// This is the response for the cancellation request
type CancelPlanResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPlanResponseProto) Reset()         { *m = CancelPlanResponseProto{} }
func (m *CancelPlanResponseProto) String() string { return proto.CompactTextString(m) }
func (*CancelPlanResponseProto) ProtoMessage()    {}
func (*CancelPlanResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{23}
}

func (m *CancelPlanResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPlanResponseProto.Unmarshal(m, b)
}
func (m *CancelPlanResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPlanResponseProto.Marshal(b, m, deterministic)
}
func (m *CancelPlanResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPlanResponseProto.Merge(m, src)
}
func (m *CancelPlanResponseProto) XXX_Size() int {
	return xxx_messageInfo_CancelPlanResponseProto.Size(m)
}
func (m *CancelPlanResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPlanResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPlanResponseProto proto.InternalMessageInfo

//*
// This message allows a client to query data node to see
// if a disk balancer plan is executing and if so what is
// the status.
type QueryPlanStatusRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPlanStatusRequestProto) Reset()         { *m = QueryPlanStatusRequestProto{} }
func (m *QueryPlanStatusRequestProto) String() string { return proto.CompactTextString(m) }
func (*QueryPlanStatusRequestProto) ProtoMessage()    {}
func (*QueryPlanStatusRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{24}
}

func (m *QueryPlanStatusRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPlanStatusRequestProto.Unmarshal(m, b)
}
func (m *QueryPlanStatusRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPlanStatusRequestProto.Marshal(b, m, deterministic)
}
func (m *QueryPlanStatusRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPlanStatusRequestProto.Merge(m, src)
}
func (m *QueryPlanStatusRequestProto) XXX_Size() int {
	return xxx_messageInfo_QueryPlanStatusRequestProto.Size(m)
}
func (m *QueryPlanStatusRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPlanStatusRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPlanStatusRequestProto proto.InternalMessageInfo

//*
// This message describes a plan if it is in progress
type QueryPlanStatusResponseProto struct {
	Result               *uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	PlanID               *string  `protobuf:"bytes,2,opt,name=planID" json:"planID,omitempty"`
	CurrentStatus        *string  `protobuf:"bytes,3,opt,name=currentStatus" json:"currentStatus,omitempty"`
	PlanFile             *string  `protobuf:"bytes,4,opt,name=planFile" json:"planFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPlanStatusResponseProto) Reset()         { *m = QueryPlanStatusResponseProto{} }
func (m *QueryPlanStatusResponseProto) String() string { return proto.CompactTextString(m) }
func (*QueryPlanStatusResponseProto) ProtoMessage()    {}
func (*QueryPlanStatusResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{25}
}

func (m *QueryPlanStatusResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPlanStatusResponseProto.Unmarshal(m, b)
}
func (m *QueryPlanStatusResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPlanStatusResponseProto.Marshal(b, m, deterministic)
}
func (m *QueryPlanStatusResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPlanStatusResponseProto.Merge(m, src)
}
func (m *QueryPlanStatusResponseProto) XXX_Size() int {
	return xxx_messageInfo_QueryPlanStatusResponseProto.Size(m)
}
func (m *QueryPlanStatusResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPlanStatusResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPlanStatusResponseProto proto.InternalMessageInfo

func (m *QueryPlanStatusResponseProto) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *QueryPlanStatusResponseProto) GetPlanID() string {
	if m != nil && m.PlanID != nil {
		return *m.PlanID
	}
	return ""
}

func (m *QueryPlanStatusResponseProto) GetCurrentStatus() string {
	if m != nil && m.CurrentStatus != nil {
		return *m.CurrentStatus
	}
	return ""
}

func (m *QueryPlanStatusResponseProto) GetPlanFile() string {
	if m != nil && m.PlanFile != nil {
		return *m.PlanFile
	}
	return ""
}

//*
// This message sends a request to data node get a specific setting
// that is used by disk balancer.
type DiskBalancerSettingRequestProto struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskBalancerSettingRequestProto) Reset()         { *m = DiskBalancerSettingRequestProto{} }
func (m *DiskBalancerSettingRequestProto) String() string { return proto.CompactTextString(m) }
func (*DiskBalancerSettingRequestProto) ProtoMessage()    {}
func (*DiskBalancerSettingRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{26}
}

func (m *DiskBalancerSettingRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskBalancerSettingRequestProto.Unmarshal(m, b)
}
func (m *DiskBalancerSettingRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskBalancerSettingRequestProto.Marshal(b, m, deterministic)
}
func (m *DiskBalancerSettingRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskBalancerSettingRequestProto.Merge(m, src)
}
func (m *DiskBalancerSettingRequestProto) XXX_Size() int {
	return xxx_messageInfo_DiskBalancerSettingRequestProto.Size(m)
}
func (m *DiskBalancerSettingRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskBalancerSettingRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_DiskBalancerSettingRequestProto proto.InternalMessageInfo

func (m *DiskBalancerSettingRequestProto) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

//*
// Response that describes the value of requested disk balancer setting.
type DiskBalancerSettingResponseProto struct {
	Value                *string  `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskBalancerSettingResponseProto) Reset()         { *m = DiskBalancerSettingResponseProto{} }
func (m *DiskBalancerSettingResponseProto) String() string { return proto.CompactTextString(m) }
func (*DiskBalancerSettingResponseProto) ProtoMessage()    {}
func (*DiskBalancerSettingResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_43cce42207c5b4db, []int{27}
}

func (m *DiskBalancerSettingResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskBalancerSettingResponseProto.Unmarshal(m, b)
}
func (m *DiskBalancerSettingResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskBalancerSettingResponseProto.Marshal(b, m, deterministic)
}
func (m *DiskBalancerSettingResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskBalancerSettingResponseProto.Merge(m, src)
}
func (m *DiskBalancerSettingResponseProto) XXX_Size() int {
	return xxx_messageInfo_DiskBalancerSettingResponseProto.Size(m)
}
func (m *DiskBalancerSettingResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskBalancerSettingResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_DiskBalancerSettingResponseProto proto.InternalMessageInfo

func (m *DiskBalancerSettingResponseProto) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetReplicaVisibleLengthRequestProto)(nil), "hadoop.hdfs.GetReplicaVisibleLengthRequestProto")
	proto.RegisterType((*GetReplicaVisibleLengthResponseProto)(nil), "hadoop.hdfs.GetReplicaVisibleLengthResponseProto")
	proto.RegisterType((*RefreshNamenodesRequestProto)(nil), "hadoop.hdfs.RefreshNamenodesRequestProto")
	proto.RegisterType((*RefreshNamenodesResponseProto)(nil), "hadoop.hdfs.RefreshNamenodesResponseProto")
	proto.RegisterType((*DeleteBlockPoolRequestProto)(nil), "hadoop.hdfs.DeleteBlockPoolRequestProto")
	proto.RegisterType((*DeleteBlockPoolResponseProto)(nil), "hadoop.hdfs.DeleteBlockPoolResponseProto")
	proto.RegisterType((*GetBlockLocalPathInfoRequestProto)(nil), "hadoop.hdfs.GetBlockLocalPathInfoRequestProto")
	proto.RegisterType((*GetBlockLocalPathInfoResponseProto)(nil), "hadoop.hdfs.GetBlockLocalPathInfoResponseProto")
	proto.RegisterType((*ShutdownDatanodeRequestProto)(nil), "hadoop.hdfs.ShutdownDatanodeRequestProto")
	proto.RegisterType((*ShutdownDatanodeResponseProto)(nil), "hadoop.hdfs.ShutdownDatanodeResponseProto")
	proto.RegisterType((*EvictWritersRequestProto)(nil), "hadoop.hdfs.EvictWritersRequestProto")
	proto.RegisterType((*EvictWritersResponseProto)(nil), "hadoop.hdfs.EvictWritersResponseProto")
	proto.RegisterType((*GetDatanodeInfoRequestProto)(nil), "hadoop.hdfs.GetDatanodeInfoRequestProto")
	proto.RegisterType((*GetDatanodeInfoResponseProto)(nil), "hadoop.hdfs.GetDatanodeInfoResponseProto")
	proto.RegisterType((*GetVolumeReportRequestProto)(nil), "hadoop.hdfs.GetVolumeReportRequestProto")
	proto.RegisterType((*GetVolumeReportResponseProto)(nil), "hadoop.hdfs.GetVolumeReportResponseProto")
	proto.RegisterType((*TriggerBlockReportRequestProto)(nil), "hadoop.hdfs.TriggerBlockReportRequestProto")
	proto.RegisterType((*TriggerBlockReportResponseProto)(nil), "hadoop.hdfs.TriggerBlockReportResponseProto")
	proto.RegisterType((*GetBalancerBandwidthRequestProto)(nil), "hadoop.hdfs.GetBalancerBandwidthRequestProto")
	proto.RegisterType((*GetBalancerBandwidthResponseProto)(nil), "hadoop.hdfs.GetBalancerBandwidthResponseProto")
	proto.RegisterType((*SubmitDiskBalancerPlanRequestProto)(nil), "hadoop.hdfs.SubmitDiskBalancerPlanRequestProto")
	proto.RegisterType((*SubmitDiskBalancerPlanResponseProto)(nil), "hadoop.hdfs.SubmitDiskBalancerPlanResponseProto")
	proto.RegisterType((*CancelPlanRequestProto)(nil), "hadoop.hdfs.CancelPlanRequestProto")
	proto.RegisterType((*CancelPlanResponseProto)(nil), "hadoop.hdfs.CancelPlanResponseProto")
	proto.RegisterType((*QueryPlanStatusRequestProto)(nil), "hadoop.hdfs.QueryPlanStatusRequestProto")
	proto.RegisterType((*QueryPlanStatusResponseProto)(nil), "hadoop.hdfs.QueryPlanStatusResponseProto")
	proto.RegisterType((*DiskBalancerSettingRequestProto)(nil), "hadoop.hdfs.DiskBalancerSettingRequestProto")
	proto.RegisterType((*DiskBalancerSettingResponseProto)(nil), "hadoop.hdfs.DiskBalancerSettingResponseProto")
}

func init() { proto.RegisterFile("ClientDatanodeProtocol.proto", fileDescriptor_43cce42207c5b4db) }

var fileDescriptor_43cce42207c5b4db = []byte{
	// 1164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0x97, 0xf3, 0xa7, 0x4a, 0x26, 0x94, 0x56, 0xab, 0xf6, 0x7a, 0x75, 0x2e, 0xc9, 0xd5, 0x49,
	0xd0, 0x15, 0xe8, 0x35, 0x04, 0x15, 0xf1, 0x54, 0x29, 0xc9, 0x95, 0xa8, 0x22, 0xa0, 0xd4, 0x57,
	0xc2, 0x0b, 0x48, 0x6c, 0xec, 0x39, 0x9f, 0x15, 0xdf, 0xee, 0x75, 0xbd, 0x4e, 0x1b, 0x21, 0x21,
	0xf1, 0x86, 0x84, 0x90, 0xf8, 0x06, 0xf0, 0x31, 0x78, 0xe4, 0xa3, 0x21, 0xaf, 0x7d, 0xc9, 0xae,
	0xed, 0xf3, 0x1d, 0x88, 0xa7, 0xf3, 0xce, 0xfc, 0x66, 0x67, 0xf6, 0xb7, 0x3b, 0xfb, 0xdb, 0x83,
	0xd6, 0x51, 0x14, 0x22, 0x93, 0x3d, 0x2a, 0x29, 0xe3, 0x3e, 0x9e, 0x0a, 0x2e, 0xb9, 0xc7, 0xa3,
	0xee, 0x38, 0xfd, 0x20, 0x6b, 0x43, 0xea, 0x73, 0x3e, 0xee, 0x0e, 0xfd, 0x41, 0x6c, 0xbf, 0xdf,
	0x47, 0x2f, 0x11, 0xa1, 0xbc, 0xca, 0x9c, 0x36, 0xa4, 0xd6, 0xfc, 0x7b, 0xc3, 0x45, 0x8f, 0xb3,
	0x41, 0x18, 0x24, 0x82, 0xca, 0x90, 0x33, 0x73, 0x1e, 0xe7, 0x3b, 0xd8, 0x3e, 0x46, 0xe9, 0xe2,
	0x38, 0x0a, 0x3d, 0x7a, 0x16, 0xc6, 0xe1, 0x79, 0x84, 0x27, 0xc8, 0x02, 0x39, 0x74, 0xf1, 0x4d,
	0x82, 0xb1, 0x54, 0x78, 0xf2, 0x0c, 0x96, 0xcf, 0x23, 0xee, 0x5d, 0x34, 0xad, 0xf6, 0x42, 0x67,
	0x6d, 0x7f, 0xab, 0xab, 0xa5, 0xef, 0xbe, 0x78, 0x27, 0x91, 0xf9, 0xe8, 0x1f, 0xa6, 0x08, 0x85,
	0x77, 0x33, 0xb4, 0xf3, 0x1c, 0x76, 0xa6, 0xce, 0x1e, 0x8f, 0x39, 0x8b, 0xb3, 0x65, 0x91, 0x06,
	0xdc, 0x8a, 0x94, 0x59, 0xcd, 0xbf, 0xe4, 0xe6, 0x23, 0x67, 0x13, 0x5a, 0x2e, 0x0e, 0x04, 0xc6,
	0xc3, 0xaf, 0xe9, 0x08, 0x53, 0x1a, 0x62, 0xbd, 0x2c, 0x67, 0x0b, 0x36, 0xca, 0x7e, 0x6d, 0x62,
	0xe7, 0x15, 0xac, 0xf7, 0x30, 0x42, 0x89, 0x59, 0x6d, 0x9c, 0x47, 0xc6, 0xb2, 0x5a, 0xb0, 0x7a,
	0x3e, 0x71, 0xa8, 0xd4, 0xab, 0xee, 0x8d, 0x81, 0xdc, 0x83, 0xe5, 0x01, 0x17, 0x1e, 0x36, 0x17,
	0xda, 0x0b, 0x9d, 0x15, 0x37, 0x1b, 0xa4, 0x35, 0x95, 0xa6, 0xd4, 0x53, 0xfe, 0x6a, 0xc1, 0xa3,
	0x63, 0x94, 0xca, 0x7b, 0xc2, 0x3d, 0x1a, 0x9d, 0x52, 0x39, 0x7c, 0xc9, 0x06, 0xfc, 0x7f, 0x20,
	0x94, 0x3c, 0x85, 0x65, 0xc9, 0x2f, 0x90, 0xa9, 0x92, 0xd6, 0xf6, 0x1f, 0x4e, 0xc2, 0x3c, 0x3e,
	0x1a, 0x71, 0xd6, 0x7d, 0x9d, 0xfa, 0xf2, 0x00, 0x85, 0x73, 0xfe, 0xb0, 0xc0, 0x99, 0x52, 0x8d,
	0xbe, 0x01, 0xff, 0xb1, 0x9c, 0x16, 0xac, 0x46, 0x93, 0x49, 0x55, 0x49, 0xab, 0xee, 0x8d, 0x81,
	0xec, 0xc0, 0x6d, 0x35, 0xf8, 0x0a, 0x25, 0x55, 0x88, 0x45, 0x85, 0x30, 0x8d, 0xce, 0x73, 0x68,
	0xf5, 0x87, 0x89, 0xf4, 0xf9, 0x5b, 0x36, 0x39, 0xeb, 0x06, 0x53, 0x9b, 0x00, 0x03, 0x2e, 0xbe,
	0x19, 0x07, 0x82, 0xfa, 0xa8, 0xea, 0x5b, 0x71, 0x35, 0x4b, 0x7a, 0x06, 0xca, 0xf1, 0xfa, 0x86,
	0xd8, 0xd0, 0x7c, 0x71, 0x19, 0x7a, 0xf2, 0x5b, 0x11, 0x4a, 0x14, 0xe6, 0x01, 0x5a, 0x87, 0x87,
	0xa6, 0x4f, 0x0f, 0xdc, 0x80, 0xf5, 0x63, 0xbc, 0x6e, 0xc0, 0xe2, 0x16, 0x3a, 0x14, 0x5a, 0x25,
	0xb7, 0xce, 0xe9, 0x41, 0x4e, 0x4e, 0xea, 0xc9, 0x79, 0xdd, 0x36, 0x78, 0x9d, 0x84, 0x9e, 0x4c,
	0x50, 0x19, 0xb7, 0x37, 0x51, 0x79, 0x05, 0x67, 0x3c, 0x4a, 0x46, 0xe8, 0xe2, 0x98, 0x0b, 0x69,
	0x54, 0xe0, 0xab, 0x0a, 0x4c, 0xb7, 0x5e, 0x41, 0x0f, 0xe0, 0x52, 0x39, 0xf3, 0x12, 0x16, 0x3b,
	0x6b, 0xfb, 0x3b, 0x95, 0x25, 0x9c, 0x5d, 0xc3, 0xb2, 0x1a, 0xb4, 0x38, 0xe7, 0x07, 0xd8, 0x7c,
	0x2d, 0xc2, 0x20, 0x40, 0xa1, 0x0e, 0x40, 0xb9, 0x0e, 0xd2, 0x86, 0xb5, 0x90, 0x79, 0x02, 0x47,
	0xc8, 0x24, 0x8d, 0xf2, 0x3d, 0xd2, 0x4d, 0xe9, 0x41, 0x61, 0xec, 0xc0, 0xf7, 0x05, 0xc6, 0x71,
	0x73, 0xa1, 0x6d, 0xa5, 0x07, 0xe5, 0xda, 0xe0, 0x3c, 0x82, 0xad, 0xaa, 0x0c, 0xfa, 0x5e, 0x38,
	0xd0, 0x4e, 0x8f, 0x31, 0x8d, 0x28, 0xf3, 0x50, 0x1c, 0x52, 0xe6, 0xbf, 0x0d, 0x7d, 0xf3, 0x92,
	0x72, 0x0e, 0xb2, 0xc6, 0x2b, 0x63, 0x74, 0x4e, 0xd2, 0x96, 0x9f, 0x78, 0xf2, 0xdb, 0xe6, 0xc6,
	0xe0, 0xfc, 0x65, 0x81, 0xd3, 0x4f, 0xce, 0x47, 0xa1, 0xec, 0x85, 0xf1, 0xc5, 0x64, 0xaa, 0xd3,
	0x88, 0x32, 0x63, 0xc1, 0x0d, 0xb8, 0x35, 0x8e, 0x28, 0x7b, 0xd9, 0xcb, 0x2f, 0x8d, 0x7c, 0x44,
	0x08, 0x2c, 0xa5, 0x5f, 0x79, 0x2b, 0xa8, 0xef, 0x94, 0x9c, 0xf4, 0xf7, 0x0c, 0x45, 0x1c, 0x72,
	0xd6, 0x5c, 0x6c, 0x5b, 0x9d, 0x25, 0x57, 0x37, 0x91, 0x0e, 0xdc, 0x09, 0x03, 0xc6, 0x05, 0xf6,
	0xa8, 0xc4, 0xa3, 0x21, 0x7a, 0x17, 0xcd, 0xa5, 0xb6, 0xd5, 0x59, 0x71, 0x8b, 0x66, 0x62, 0xc3,
	0x4a, 0x1a, 0xf8, 0x45, 0x18, 0x61, 0x73, 0x59, 0xe5, 0xb8, 0x1e, 0x3b, 0xbb, 0xb0, 0x3d, 0xad,
	0x72, 0x9d, 0xc8, 0x3d, 0x68, 0x1c, 0xa5, 0xae, 0x68, 0xde, 0x45, 0x39, 0x0f, 0xe1, 0x81, 0x1e,
	0x51, 0xe8, 0x90, 0x57, 0x09, 0x8a, 0xab, 0xd4, 0xd3, 0x97, 0x54, 0x26, 0x66, 0x77, 0xfd, 0x6e,
	0x41, 0xab, 0xe4, 0x2f, 0xdc, 0xfb, 0x02, 0xe3, 0x24, 0x92, 0x4d, 0xab, 0x6d, 0x75, 0x6e, 0xbb,
	0xf9, 0x48, 0x2b, 0x25, 0x3b, 0x2b, 0x13, 0x7e, 0x77, 0xe0, 0xb6, 0x97, 0x08, 0x81, 0x4c, 0x66,
	0xb3, 0x29, 0x36, 0x57, 0x5d, 0xd3, 0x68, 0xb0, 0xb4, 0xa4, 0x00, 0x37, 0x2c, 0x7d, 0x0a, 0x5b,
	0x3a, 0x3f, 0x7d, 0x94, 0x32, 0x64, 0x81, 0xc1, 0xc3, 0x5d, 0x58, 0xbc, 0xc0, 0xab, 0x9c, 0x84,
	0xf4, 0xd3, 0xf9, 0x1c, 0xda, 0x95, 0x41, 0xfa, 0x52, 0xee, 0xc1, 0xf2, 0x25, 0x8d, 0x12, 0xcc,
	0xe3, 0xb2, 0xc1, 0xfe, 0xdf, 0x77, 0x60, 0xa3, 0x5a, 0xc7, 0xfb, 0x28, 0x2e, 0x43, 0x0f, 0xc9,
	0x4f, 0xf0, 0x20, 0xa8, 0x96, 0x48, 0xb2, 0x67, 0xb4, 0xea, 0x1c, 0x32, 0x6d, 0x7f, 0x32, 0x5f,
	0x84, 0x5e, 0x77, 0x08, 0x77, 0x45, 0x41, 0x42, 0xc9, 0x63, 0x63, 0x9a, 0x3a, 0x05, 0xb6, 0x3f,
	0x9c, 0x01, 0xd5, 0x53, 0x0d, 0xe0, 0x8e, 0x6f, 0x2a, 0x27, 0xe9, 0x98, 0xb7, 0xd1, 0x74, 0xa9,
	0xb6, 0x1f, 0xd7, 0x23, 0xf5, 0x3c, 0xef, 0xe0, 0x7e, 0x50, 0x25, 0x79, 0xa4, 0x5b, 0xa4, 0xa7,
	0x5e, 0xa4, 0xed, 0xa7, 0xf3, 0xe0, 0x0b, 0x64, 0xc6, 0x05, 0x2d, 0x2a, 0x90, 0x59, 0x27, 0x75,
	0x05, 0x32, 0x6b, 0x55, 0x8d, 0x7c, 0x0f, 0xef, 0xa1, 0xa6, 0x5c, 0x64, 0xd7, 0x94, 0xec, 0x29,
	0x82, 0x67, 0x7f, 0x50, 0x03, 0x2b, 0xec, 0x55, 0x60, 0x8a, 0x5b, 0x61, 0xaf, 0x6a, 0x94, 0xb1,
	0xb0, 0x57, 0xb5, 0x22, 0x99, 0xe5, 0xd1, 0x25, 0xac, 0x9c, 0x67, 0x9a, 0xfe, 0x95, 0xf3, 0x4c,
	0x97, 0xc2, 0x9f, 0x2d, 0x68, 0xaa, 0x3e, 0x33, 0x1e, 0xc3, 0xf9, 0x85, 0x51, 0xd1, 0x36, 0x15,
	0x30, 0x23, 0xf5, 0xfe, 0x9c, 0x21, 0x7a, 0x0d, 0x09, 0xdc, 0x8b, 0x25, 0x15, 0x45, 0x28, 0x79,
	0x62, 0x6e, 0x7b, 0x05, 0xc4, 0x48, 0xdd, 0x9d, 0x03, 0xae, 0xa7, 0xfd, 0xcd, 0x82, 0x56, 0x14,
	0xc6, 0x3a, 0xe8, 0x3c, 0x4a, 0x7d, 0x63, 0x14, 0x32, 0xc4, 0x98, 0x3c, 0x33, 0x26, 0x3c, 0xa9,
	0x81, 0x1a, 0x75, 0x7c, 0xf6, 0x2f, 0xc2, 0xf4, 0x7a, 0x38, 0x10, 0x59, 0x52, 0x7b, 0xf2, 0x91,
	0x31, 0x5b, 0xfd, 0x83, 0xc3, 0xfe, 0x78, 0x26, 0xb8, 0xc0, 0x7b, 0x50, 0xf1, 0x2e, 0x28, 0xf0,
	0x3e, 0xeb, 0x79, 0x61, 0x77, 0xe7, 0x80, 0xeb, 0x69, 0x7f, 0x84, 0x46, 0x5c, 0x29, 0xc8, 0xc4,
	0xbc, 0x57, 0x66, 0xbf, 0x37, 0xec, 0xbd, 0xb9, 0x02, 0xf4, 0xe4, 0x1e, 0x34, 0x3c, 0x25, 0xda,
	0xa5, 0xe4, 0xe6, 0x1b, 0xb4, 0xfa, 0x2d, 0x60, 0xef, 0x4c, 0x05, 0xe9, 0x49, 0x22, 0xb8, 0xff,
	0x26, 0x95, 0xf7, 0x52, 0x0e, 0xb3, 0x85, 0x6b, 0x9e, 0x08, 0x85, 0x16, 0xae, 0x7d, 0x2c, 0x24,
	0xd0, 0x48, 0xaf, 0xa4, 0xb2, 0x10, 0x13, 0xf3, 0x38, 0xcc, 0xd0, 0x77, 0xfb, 0xc9, 0x6c, 0xb4,
	0x96, 0xf6, 0xf0, 0x4b, 0xd8, 0xe5, 0x22, 0xe8, 0xd2, 0x31, 0xf5, 0x86, 0x68, 0x84, 0x8e, 0x8d,
	0xbf, 0xd2, 0x87, 0x53, 0xfe, 0xb0, 0xab, 0xdf, 0xf8, 0x17, 0xcb, 0xfa, 0xd3, 0xb2, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xbb, 0x47, 0x4e, 0xb0, 0xd5, 0x0f, 0x00, 0x00,
}
