// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encryption.proto

package hadoop_hdfs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReencryptActionProto int32

const (
	ReencryptActionProto_CANCEL_REENCRYPT ReencryptActionProto = 1
	ReencryptActionProto_START_REENCRYPT  ReencryptActionProto = 2
)

var ReencryptActionProto_name = map[int32]string{
	1: "CANCEL_REENCRYPT",
	2: "START_REENCRYPT",
}

var ReencryptActionProto_value = map[string]int32{
	"CANCEL_REENCRYPT": 1,
	"START_REENCRYPT":  2,
}

func (x ReencryptActionProto) Enum() *ReencryptActionProto {
	p := new(ReencryptActionProto)
	*p = x
	return p
}

func (x ReencryptActionProto) String() string {
	return proto.EnumName(ReencryptActionProto_name, int32(x))
}

func (x *ReencryptActionProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReencryptActionProto_value, data, "ReencryptActionProto")
	if err != nil {
		return err
	}
	*x = ReencryptActionProto(value)
	return nil
}

func (ReencryptActionProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{0}
}

type ReencryptionStateProto int32

const (
	ReencryptionStateProto_SUBMITTED  ReencryptionStateProto = 1
	ReencryptionStateProto_PROCESSING ReencryptionStateProto = 2
	ReencryptionStateProto_COMPLETED  ReencryptionStateProto = 3
)

var ReencryptionStateProto_name = map[int32]string{
	1: "SUBMITTED",
	2: "PROCESSING",
	3: "COMPLETED",
}

var ReencryptionStateProto_value = map[string]int32{
	"SUBMITTED":  1,
	"PROCESSING": 2,
	"COMPLETED":  3,
}

func (x ReencryptionStateProto) Enum() *ReencryptionStateProto {
	p := new(ReencryptionStateProto)
	*p = x
	return p
}

func (x ReencryptionStateProto) String() string {
	return proto.EnumName(ReencryptionStateProto_name, int32(x))
}

func (x *ReencryptionStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReencryptionStateProto_value, data, "ReencryptionStateProto")
	if err != nil {
		return err
	}
	*x = ReencryptionStateProto(value)
	return nil
}

func (ReencryptionStateProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{1}
}

type CreateEncryptionZoneRequestProto struct {
	Src                  *string  `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	KeyName              *string  `protobuf:"bytes,2,opt,name=keyName" json:"keyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEncryptionZoneRequestProto) Reset()         { *m = CreateEncryptionZoneRequestProto{} }
func (m *CreateEncryptionZoneRequestProto) String() string { return proto.CompactTextString(m) }
func (*CreateEncryptionZoneRequestProto) ProtoMessage()    {}
func (*CreateEncryptionZoneRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{0}
}

func (m *CreateEncryptionZoneRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEncryptionZoneRequestProto.Unmarshal(m, b)
}
func (m *CreateEncryptionZoneRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEncryptionZoneRequestProto.Marshal(b, m, deterministic)
}
func (m *CreateEncryptionZoneRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEncryptionZoneRequestProto.Merge(m, src)
}
func (m *CreateEncryptionZoneRequestProto) XXX_Size() int {
	return xxx_messageInfo_CreateEncryptionZoneRequestProto.Size(m)
}
func (m *CreateEncryptionZoneRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEncryptionZoneRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEncryptionZoneRequestProto proto.InternalMessageInfo

func (m *CreateEncryptionZoneRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *CreateEncryptionZoneRequestProto) GetKeyName() string {
	if m != nil && m.KeyName != nil {
		return *m.KeyName
	}
	return ""
}

type CreateEncryptionZoneResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEncryptionZoneResponseProto) Reset()         { *m = CreateEncryptionZoneResponseProto{} }
func (m *CreateEncryptionZoneResponseProto) String() string { return proto.CompactTextString(m) }
func (*CreateEncryptionZoneResponseProto) ProtoMessage()    {}
func (*CreateEncryptionZoneResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{1}
}

func (m *CreateEncryptionZoneResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEncryptionZoneResponseProto.Unmarshal(m, b)
}
func (m *CreateEncryptionZoneResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEncryptionZoneResponseProto.Marshal(b, m, deterministic)
}
func (m *CreateEncryptionZoneResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEncryptionZoneResponseProto.Merge(m, src)
}
func (m *CreateEncryptionZoneResponseProto) XXX_Size() int {
	return xxx_messageInfo_CreateEncryptionZoneResponseProto.Size(m)
}
func (m *CreateEncryptionZoneResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEncryptionZoneResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEncryptionZoneResponseProto proto.InternalMessageInfo

type ListEncryptionZonesRequestProto struct {
	Id                   *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEncryptionZonesRequestProto) Reset()         { *m = ListEncryptionZonesRequestProto{} }
func (m *ListEncryptionZonesRequestProto) String() string { return proto.CompactTextString(m) }
func (*ListEncryptionZonesRequestProto) ProtoMessage()    {}
func (*ListEncryptionZonesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{2}
}

func (m *ListEncryptionZonesRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEncryptionZonesRequestProto.Unmarshal(m, b)
}
func (m *ListEncryptionZonesRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEncryptionZonesRequestProto.Marshal(b, m, deterministic)
}
func (m *ListEncryptionZonesRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEncryptionZonesRequestProto.Merge(m, src)
}
func (m *ListEncryptionZonesRequestProto) XXX_Size() int {
	return xxx_messageInfo_ListEncryptionZonesRequestProto.Size(m)
}
func (m *ListEncryptionZonesRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEncryptionZonesRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListEncryptionZonesRequestProto proto.InternalMessageInfo

func (m *ListEncryptionZonesRequestProto) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type EncryptionZoneProto struct {
	Id                    *int64                      `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Path                  *string                     `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Suite                 *CipherSuiteProto           `protobuf:"varint,3,req,name=suite,enum=hadoop.hdfs.CipherSuiteProto" json:"suite,omitempty"`
	CryptoProtocolVersion *CryptoProtocolVersionProto `protobuf:"varint,4,req,name=cryptoProtocolVersion,enum=hadoop.hdfs.CryptoProtocolVersionProto" json:"cryptoProtocolVersion,omitempty"`
	KeyName               *string                     `protobuf:"bytes,5,req,name=keyName" json:"keyName,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                    `json:"-"`
	XXX_unrecognized      []byte                      `json:"-"`
	XXX_sizecache         int32                       `json:"-"`
}

func (m *EncryptionZoneProto) Reset()         { *m = EncryptionZoneProto{} }
func (m *EncryptionZoneProto) String() string { return proto.CompactTextString(m) }
func (*EncryptionZoneProto) ProtoMessage()    {}
func (*EncryptionZoneProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{3}
}

func (m *EncryptionZoneProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptionZoneProto.Unmarshal(m, b)
}
func (m *EncryptionZoneProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptionZoneProto.Marshal(b, m, deterministic)
}
func (m *EncryptionZoneProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptionZoneProto.Merge(m, src)
}
func (m *EncryptionZoneProto) XXX_Size() int {
	return xxx_messageInfo_EncryptionZoneProto.Size(m)
}
func (m *EncryptionZoneProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptionZoneProto.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptionZoneProto proto.InternalMessageInfo

func (m *EncryptionZoneProto) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *EncryptionZoneProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *EncryptionZoneProto) GetSuite() CipherSuiteProto {
	if m != nil && m.Suite != nil {
		return *m.Suite
	}
	return CipherSuiteProto_UNKNOWN
}

func (m *EncryptionZoneProto) GetCryptoProtocolVersion() CryptoProtocolVersionProto {
	if m != nil && m.CryptoProtocolVersion != nil {
		return *m.CryptoProtocolVersion
	}
	return CryptoProtocolVersionProto_UNKNOWN_PROTOCOL_VERSION
}

func (m *EncryptionZoneProto) GetKeyName() string {
	if m != nil && m.KeyName != nil {
		return *m.KeyName
	}
	return ""
}

type ListEncryptionZonesResponseProto struct {
	Zones                []*EncryptionZoneProto `protobuf:"bytes,1,rep,name=zones" json:"zones,omitempty"`
	HasMore              *bool                  `protobuf:"varint,2,req,name=hasMore" json:"hasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListEncryptionZonesResponseProto) Reset()         { *m = ListEncryptionZonesResponseProto{} }
func (m *ListEncryptionZonesResponseProto) String() string { return proto.CompactTextString(m) }
func (*ListEncryptionZonesResponseProto) ProtoMessage()    {}
func (*ListEncryptionZonesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{4}
}

func (m *ListEncryptionZonesResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEncryptionZonesResponseProto.Unmarshal(m, b)
}
func (m *ListEncryptionZonesResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEncryptionZonesResponseProto.Marshal(b, m, deterministic)
}
func (m *ListEncryptionZonesResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEncryptionZonesResponseProto.Merge(m, src)
}
func (m *ListEncryptionZonesResponseProto) XXX_Size() int {
	return xxx_messageInfo_ListEncryptionZonesResponseProto.Size(m)
}
func (m *ListEncryptionZonesResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEncryptionZonesResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListEncryptionZonesResponseProto proto.InternalMessageInfo

func (m *ListEncryptionZonesResponseProto) GetZones() []*EncryptionZoneProto {
	if m != nil {
		return m.Zones
	}
	return nil
}

func (m *ListEncryptionZonesResponseProto) GetHasMore() bool {
	if m != nil && m.HasMore != nil {
		return *m.HasMore
	}
	return false
}

type ReencryptEncryptionZoneRequestProto struct {
	Action               *ReencryptActionProto `protobuf:"varint,1,req,name=action,enum=hadoop.hdfs.ReencryptActionProto" json:"action,omitempty"`
	Zone                 *string               `protobuf:"bytes,2,req,name=zone" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReencryptEncryptionZoneRequestProto) Reset()         { *m = ReencryptEncryptionZoneRequestProto{} }
func (m *ReencryptEncryptionZoneRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReencryptEncryptionZoneRequestProto) ProtoMessage()    {}
func (*ReencryptEncryptionZoneRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{5}
}

func (m *ReencryptEncryptionZoneRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReencryptEncryptionZoneRequestProto.Unmarshal(m, b)
}
func (m *ReencryptEncryptionZoneRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReencryptEncryptionZoneRequestProto.Marshal(b, m, deterministic)
}
func (m *ReencryptEncryptionZoneRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReencryptEncryptionZoneRequestProto.Merge(m, src)
}
func (m *ReencryptEncryptionZoneRequestProto) XXX_Size() int {
	return xxx_messageInfo_ReencryptEncryptionZoneRequestProto.Size(m)
}
func (m *ReencryptEncryptionZoneRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReencryptEncryptionZoneRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReencryptEncryptionZoneRequestProto proto.InternalMessageInfo

func (m *ReencryptEncryptionZoneRequestProto) GetAction() ReencryptActionProto {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ReencryptActionProto_CANCEL_REENCRYPT
}

func (m *ReencryptEncryptionZoneRequestProto) GetZone() string {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return ""
}

type ReencryptEncryptionZoneResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReencryptEncryptionZoneResponseProto) Reset()         { *m = ReencryptEncryptionZoneResponseProto{} }
func (m *ReencryptEncryptionZoneResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReencryptEncryptionZoneResponseProto) ProtoMessage()    {}
func (*ReencryptEncryptionZoneResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{6}
}

func (m *ReencryptEncryptionZoneResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReencryptEncryptionZoneResponseProto.Unmarshal(m, b)
}
func (m *ReencryptEncryptionZoneResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReencryptEncryptionZoneResponseProto.Marshal(b, m, deterministic)
}
func (m *ReencryptEncryptionZoneResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReencryptEncryptionZoneResponseProto.Merge(m, src)
}
func (m *ReencryptEncryptionZoneResponseProto) XXX_Size() int {
	return xxx_messageInfo_ReencryptEncryptionZoneResponseProto.Size(m)
}
func (m *ReencryptEncryptionZoneResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReencryptEncryptionZoneResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReencryptEncryptionZoneResponseProto proto.InternalMessageInfo

type ListReencryptionStatusRequestProto struct {
	Id                   *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReencryptionStatusRequestProto) Reset()         { *m = ListReencryptionStatusRequestProto{} }
func (m *ListReencryptionStatusRequestProto) String() string { return proto.CompactTextString(m) }
func (*ListReencryptionStatusRequestProto) ProtoMessage()    {}
func (*ListReencryptionStatusRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{7}
}

func (m *ListReencryptionStatusRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReencryptionStatusRequestProto.Unmarshal(m, b)
}
func (m *ListReencryptionStatusRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReencryptionStatusRequestProto.Marshal(b, m, deterministic)
}
func (m *ListReencryptionStatusRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReencryptionStatusRequestProto.Merge(m, src)
}
func (m *ListReencryptionStatusRequestProto) XXX_Size() int {
	return xxx_messageInfo_ListReencryptionStatusRequestProto.Size(m)
}
func (m *ListReencryptionStatusRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReencryptionStatusRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListReencryptionStatusRequestProto proto.InternalMessageInfo

func (m *ListReencryptionStatusRequestProto) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type ZoneReencryptionStatusProto struct {
	Id                   *int64                  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Path                 *string                 `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	State                *ReencryptionStateProto `protobuf:"varint,3,req,name=state,enum=hadoop.hdfs.ReencryptionStateProto" json:"state,omitempty"`
	EzKeyVersionName     *string                 `protobuf:"bytes,4,req,name=ezKeyVersionName" json:"ezKeyVersionName,omitempty"`
	SubmissionTime       *int64                  `protobuf:"varint,5,req,name=submissionTime" json:"submissionTime,omitempty"`
	Canceled             *bool                   `protobuf:"varint,6,req,name=canceled" json:"canceled,omitempty"`
	NumReencrypted       *int64                  `protobuf:"varint,7,req,name=numReencrypted" json:"numReencrypted,omitempty"`
	NumFailures          *int64                  `protobuf:"varint,8,req,name=numFailures" json:"numFailures,omitempty"`
	CompletionTime       *int64                  `protobuf:"varint,9,opt,name=completionTime" json:"completionTime,omitempty"`
	LastFile             *string                 `protobuf:"bytes,10,opt,name=lastFile" json:"lastFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ZoneReencryptionStatusProto) Reset()         { *m = ZoneReencryptionStatusProto{} }
func (m *ZoneReencryptionStatusProto) String() string { return proto.CompactTextString(m) }
func (*ZoneReencryptionStatusProto) ProtoMessage()    {}
func (*ZoneReencryptionStatusProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{8}
}

func (m *ZoneReencryptionStatusProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneReencryptionStatusProto.Unmarshal(m, b)
}
func (m *ZoneReencryptionStatusProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneReencryptionStatusProto.Marshal(b, m, deterministic)
}
func (m *ZoneReencryptionStatusProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneReencryptionStatusProto.Merge(m, src)
}
func (m *ZoneReencryptionStatusProto) XXX_Size() int {
	return xxx_messageInfo_ZoneReencryptionStatusProto.Size(m)
}
func (m *ZoneReencryptionStatusProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneReencryptionStatusProto.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneReencryptionStatusProto proto.InternalMessageInfo

func (m *ZoneReencryptionStatusProto) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ZoneReencryptionStatusProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *ZoneReencryptionStatusProto) GetState() ReencryptionStateProto {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ReencryptionStateProto_SUBMITTED
}

func (m *ZoneReencryptionStatusProto) GetEzKeyVersionName() string {
	if m != nil && m.EzKeyVersionName != nil {
		return *m.EzKeyVersionName
	}
	return ""
}

func (m *ZoneReencryptionStatusProto) GetSubmissionTime() int64 {
	if m != nil && m.SubmissionTime != nil {
		return *m.SubmissionTime
	}
	return 0
}

func (m *ZoneReencryptionStatusProto) GetCanceled() bool {
	if m != nil && m.Canceled != nil {
		return *m.Canceled
	}
	return false
}

func (m *ZoneReencryptionStatusProto) GetNumReencrypted() int64 {
	if m != nil && m.NumReencrypted != nil {
		return *m.NumReencrypted
	}
	return 0
}

func (m *ZoneReencryptionStatusProto) GetNumFailures() int64 {
	if m != nil && m.NumFailures != nil {
		return *m.NumFailures
	}
	return 0
}

func (m *ZoneReencryptionStatusProto) GetCompletionTime() int64 {
	if m != nil && m.CompletionTime != nil {
		return *m.CompletionTime
	}
	return 0
}

func (m *ZoneReencryptionStatusProto) GetLastFile() string {
	if m != nil && m.LastFile != nil {
		return *m.LastFile
	}
	return ""
}

type ListReencryptionStatusResponseProto struct {
	Statuses             []*ZoneReencryptionStatusProto `protobuf:"bytes,1,rep,name=statuses" json:"statuses,omitempty"`
	HasMore              *bool                          `protobuf:"varint,2,req,name=hasMore" json:"hasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListReencryptionStatusResponseProto) Reset()         { *m = ListReencryptionStatusResponseProto{} }
func (m *ListReencryptionStatusResponseProto) String() string { return proto.CompactTextString(m) }
func (*ListReencryptionStatusResponseProto) ProtoMessage()    {}
func (*ListReencryptionStatusResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{9}
}

func (m *ListReencryptionStatusResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReencryptionStatusResponseProto.Unmarshal(m, b)
}
func (m *ListReencryptionStatusResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReencryptionStatusResponseProto.Marshal(b, m, deterministic)
}
func (m *ListReencryptionStatusResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReencryptionStatusResponseProto.Merge(m, src)
}
func (m *ListReencryptionStatusResponseProto) XXX_Size() int {
	return xxx_messageInfo_ListReencryptionStatusResponseProto.Size(m)
}
func (m *ListReencryptionStatusResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReencryptionStatusResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_ListReencryptionStatusResponseProto proto.InternalMessageInfo

func (m *ListReencryptionStatusResponseProto) GetStatuses() []*ZoneReencryptionStatusProto {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *ListReencryptionStatusResponseProto) GetHasMore() bool {
	if m != nil && m.HasMore != nil {
		return *m.HasMore
	}
	return false
}

type GetEZForPathRequestProto struct {
	Src                  *string  `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEZForPathRequestProto) Reset()         { *m = GetEZForPathRequestProto{} }
func (m *GetEZForPathRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetEZForPathRequestProto) ProtoMessage()    {}
func (*GetEZForPathRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{10}
}

func (m *GetEZForPathRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEZForPathRequestProto.Unmarshal(m, b)
}
func (m *GetEZForPathRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEZForPathRequestProto.Marshal(b, m, deterministic)
}
func (m *GetEZForPathRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEZForPathRequestProto.Merge(m, src)
}
func (m *GetEZForPathRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetEZForPathRequestProto.Size(m)
}
func (m *GetEZForPathRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEZForPathRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetEZForPathRequestProto proto.InternalMessageInfo

func (m *GetEZForPathRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetEZForPathResponseProto struct {
	Zone                 *EncryptionZoneProto `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEZForPathResponseProto) Reset()         { *m = GetEZForPathResponseProto{} }
func (m *GetEZForPathResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetEZForPathResponseProto) ProtoMessage()    {}
func (*GetEZForPathResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{11}
}

func (m *GetEZForPathResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEZForPathResponseProto.Unmarshal(m, b)
}
func (m *GetEZForPathResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEZForPathResponseProto.Marshal(b, m, deterministic)
}
func (m *GetEZForPathResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEZForPathResponseProto.Merge(m, src)
}
func (m *GetEZForPathResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetEZForPathResponseProto.Size(m)
}
func (m *GetEZForPathResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEZForPathResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetEZForPathResponseProto proto.InternalMessageInfo

func (m *GetEZForPathResponseProto) GetZone() *EncryptionZoneProto {
	if m != nil {
		return m.Zone
	}
	return nil
}

func init() {
	proto.RegisterEnum("hadoop.hdfs.ReencryptActionProto", ReencryptActionProto_name, ReencryptActionProto_value)
	proto.RegisterEnum("hadoop.hdfs.ReencryptionStateProto", ReencryptionStateProto_name, ReencryptionStateProto_value)
	proto.RegisterType((*CreateEncryptionZoneRequestProto)(nil), "hadoop.hdfs.CreateEncryptionZoneRequestProto")
	proto.RegisterType((*CreateEncryptionZoneResponseProto)(nil), "hadoop.hdfs.CreateEncryptionZoneResponseProto")
	proto.RegisterType((*ListEncryptionZonesRequestProto)(nil), "hadoop.hdfs.ListEncryptionZonesRequestProto")
	proto.RegisterType((*EncryptionZoneProto)(nil), "hadoop.hdfs.EncryptionZoneProto")
	proto.RegisterType((*ListEncryptionZonesResponseProto)(nil), "hadoop.hdfs.ListEncryptionZonesResponseProto")
	proto.RegisterType((*ReencryptEncryptionZoneRequestProto)(nil), "hadoop.hdfs.ReencryptEncryptionZoneRequestProto")
	proto.RegisterType((*ReencryptEncryptionZoneResponseProto)(nil), "hadoop.hdfs.ReencryptEncryptionZoneResponseProto")
	proto.RegisterType((*ListReencryptionStatusRequestProto)(nil), "hadoop.hdfs.ListReencryptionStatusRequestProto")
	proto.RegisterType((*ZoneReencryptionStatusProto)(nil), "hadoop.hdfs.ZoneReencryptionStatusProto")
	proto.RegisterType((*ListReencryptionStatusResponseProto)(nil), "hadoop.hdfs.ListReencryptionStatusResponseProto")
	proto.RegisterType((*GetEZForPathRequestProto)(nil), "hadoop.hdfs.GetEZForPathRequestProto")
	proto.RegisterType((*GetEZForPathResponseProto)(nil), "hadoop.hdfs.GetEZForPathResponseProto")
}

func init() { proto.RegisterFile("encryption.proto", fileDescriptor_8293a649ce9418c6) }

var fileDescriptor_8293a649ce9418c6 = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xd2, 0x75, 0x6b, 0xef, 0x44, 0x89, 0xbc, 0x0d, 0x85, 0x21, 0x44, 0x96, 0xc2, 0xa8,
	0x26, 0x54, 0x89, 0x31, 0x21, 0xed, 0xb1, 0xcb, 0xd2, 0x69, 0x62, 0xeb, 0x8a, 0x5b, 0x90, 0x98,
	0x84, 0x90, 0x49, 0x0d, 0x89, 0x48, 0xe3, 0x10, 0x3b, 0x0f, 0xdb, 0x3b, 0xff, 0xc1, 0xdf, 0xf1,
	0x0f, 0x3c, 0x21, 0x3b, 0x69, 0x94, 0x94, 0xac, 0xda, 0x4b, 0x65, 0x1f, 0x1f, 0x9f, 0x7b, 0x7b,
	0xee, 0x89, 0xc1, 0xa0, 0x91, 0x97, 0xdc, 0xc4, 0x22, 0x60, 0x51, 0x3f, 0x4e, 0x98, 0x60, 0x68,
	0xd3, 0x27, 0x33, 0xc6, 0xe2, 0xbe, 0x3f, 0xfb, 0xc6, 0x77, 0x41, 0xfe, 0x66, 0x07, 0xf6, 0x08,
	0x2c, 0x27, 0xa1, 0x44, 0x50, 0xb7, 0xb8, 0x72, 0xcd, 0x22, 0x8a, 0xe9, 0xcf, 0x94, 0x72, 0x31,
	0x56, 0x97, 0x0d, 0x68, 0xf0, 0xc4, 0x33, 0x35, 0x4b, 0xef, 0xb5, 0xb1, 0x5c, 0x22, 0x13, 0x36,
	0x7e, 0xd0, 0x9b, 0x11, 0x99, 0x53, 0x53, 0xb7, 0xb4, 0x5e, 0x1b, 0x2f, 0xb6, 0x76, 0x17, 0xf6,
	0xea, 0xf5, 0x78, 0xcc, 0x22, 0x4e, 0x95, 0xa0, 0xfd, 0x1a, 0x9e, 0x5d, 0x04, 0x5c, 0x54, 0x29,
	0xbc, 0x52, 0xb3, 0x03, 0x7a, 0x30, 0x53, 0x25, 0x1b, 0x58, 0x0f, 0x66, 0xf6, 0x1f, 0x0d, 0xb6,
	0xaa, 0xfc, 0x5a, 0x1e, 0x42, 0xb0, 0x16, 0x13, 0xe1, 0x9b, 0xba, 0x6a, 0x56, 0xad, 0xd1, 0x1b,
	0x68, 0xf2, 0x34, 0x10, 0xd4, 0x6c, 0x58, 0x7a, 0xaf, 0x73, 0xf8, 0xb4, 0x5f, 0x32, 0xa3, 0xef,
	0x04, 0xb1, 0x4f, 0x93, 0x89, 0x3c, 0x57, 0x8a, 0x38, 0xe3, 0xa2, 0xcf, 0xb0, 0xa3, 0xaa, 0x31,
	0x85, 0x7a, 0x2c, 0xfc, 0x48, 0x13, 0x1e, 0xb0, 0xc8, 0x5c, 0x53, 0x22, 0x2f, 0xab, 0x22, 0x75,
	0xcc, 0x4c, 0xae, 0x5e, 0xa5, 0xec, 0x60, 0x53, 0xb5, 0x5a, 0x38, 0x28, 0xc0, 0xaa, 0x35, 0xa7,
	0x64, 0x20, 0x7a, 0x0b, 0xcd, 0x5b, 0x89, 0x9a, 0x9a, 0xd5, 0xe8, 0x6d, 0x1e, 0x5a, 0x95, 0x66,
	0x6a, 0x6c, 0xc2, 0x19, 0x5d, 0x56, 0xf5, 0x09, 0xbf, 0x64, 0x09, 0x55, 0x06, 0xb5, 0xf0, 0x62,
	0x6b, 0x0b, 0xe8, 0x62, 0x9a, 0xc7, 0x66, 0x45, 0x14, 0x8e, 0x61, 0x9d, 0x78, 0xf2, 0x44, 0x59,
	0xde, 0x39, 0xdc, 0xab, 0x54, 0x2e, 0x14, 0x06, 0x8a, 0x93, 0x95, 0xce, 0x2f, 0xc8, 0xc9, 0xc8,
	0x26, 0x16, 0x93, 0x91, 0x6b, 0x7b, 0x1f, 0x9e, 0xdf, 0x59, 0xb5, 0x1c, 0x98, 0x23, 0xb0, 0xa5,
	0x27, 0x05, 0x37, 0x60, 0xd1, 0x44, 0x10, 0x91, 0xae, 0xce, 0xcc, 0x5f, 0x1d, 0x9e, 0x64, 0x5a,
	0xcb, 0xd7, 0xee, 0x9f, 0x9d, 0x63, 0x68, 0x72, 0x41, 0x8a, 0xec, 0x74, 0xeb, 0xff, 0x6f, 0x2e,
	0x5c, 0x24, 0x48, 0xae, 0xd1, 0x01, 0x18, 0xf4, 0xf6, 0x1d, 0xbd, 0xc9, 0x47, 0xae, 0x66, 0xbd,
	0xa6, 0xa4, 0xff, 0xc3, 0xd1, 0x3e, 0x74, 0x78, 0xfa, 0x75, 0x1e, 0x70, 0x89, 0x4c, 0x83, 0x3c,
	0x15, 0x0d, 0xbc, 0x84, 0xa2, 0x5d, 0x68, 0x79, 0x24, 0xf2, 0x68, 0x48, 0x67, 0xe6, 0xba, 0x9a,
	0x60, 0xb1, 0x97, 0x1a, 0x51, 0x3a, 0x2f, 0x7a, 0xa2, 0x33, 0x73, 0x23, 0xd3, 0xa8, 0xa2, 0xc8,
	0x82, 0xcd, 0x28, 0x9d, 0x0f, 0x49, 0x10, 0xa6, 0x09, 0xe5, 0x66, 0x4b, 0x91, 0xca, 0x90, 0x54,
	0xf2, 0xd8, 0x3c, 0x0e, 0xa9, 0x58, 0x74, 0xd3, 0xb6, 0x34, 0xa9, 0x54, 0x45, 0x65, 0x37, 0x21,
	0xe1, 0x62, 0x18, 0x84, 0xd4, 0x04, 0xf5, 0x0e, 0x14, 0x7b, 0xfb, 0x97, 0x06, 0xdd, 0xbb, 0x66,
	0x56, 0x8e, 0xf2, 0x29, 0xb4, 0xb8, 0x82, 0x8b, 0x34, 0xf7, 0x2a, 0x1e, 0xaf, 0x18, 0x20, 0x2e,
	0x6e, 0xae, 0x08, 0xf6, 0x2b, 0x30, 0xcf, 0xa8, 0x70, 0xaf, 0x87, 0x2c, 0x19, 0x13, 0xe1, 0xaf,
	0x7e, 0xd8, 0xec, 0xf7, 0xf0, 0xb8, 0xca, 0x2e, 0xb7, 0x7a, 0x94, 0x27, 0x58, 0xb3, 0xb4, 0x7b,
	0x7d, 0x74, 0x8a, 0x7d, 0x30, 0x80, 0xed, 0xba, 0xef, 0x02, 0x6d, 0x83, 0xe1, 0x0c, 0x46, 0x8e,
	0x7b, 0xf1, 0x05, 0xbb, 0xee, 0xc8, 0xc1, 0x9f, 0xc6, 0x53, 0x43, 0x43, 0x5b, 0xf0, 0x70, 0x32,
	0x1d, 0xe0, 0x69, 0x09, 0xd4, 0x0f, 0x86, 0xf0, 0xa8, 0x3e, 0x6a, 0xe8, 0x01, 0xb4, 0x27, 0x1f,
	0x4e, 0x2e, 0xcf, 0xa7, 0x53, 0xf7, 0xd4, 0xd0, 0x50, 0x07, 0x60, 0x8c, 0xaf, 0x1c, 0x77, 0x32,
	0x39, 0x1f, 0x9d, 0x19, 0xba, 0x3c, 0x76, 0xae, 0x2e, 0xc7, 0x17, 0xae, 0x3c, 0x6e, 0x9c, 0x0c,
	0xe0, 0x05, 0x4b, 0xbe, 0xf7, 0x49, 0x4c, 0x3c, 0x9f, 0x56, 0xda, 0x8f, 0xf3, 0xe7, 0x29, 0x5b,
	0x9c, 0xec, 0x2c, 0xbd, 0x3e, 0xaa, 0x18, 0xff, 0xad, 0x69, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xba, 0x3d, 0x4a, 0x5b, 0x06, 0x00, 0x00,
}
