// Code generated by protoc-gen-go. DO NOT EDIT.
// source: erasurecoding.proto

package hadoop_hdfs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetErasureCodingPolicyRequestProto struct {
	Src                  *string  `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	EcPolicyName         *string  `protobuf:"bytes,2,opt,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetErasureCodingPolicyRequestProto) Reset()         { *m = SetErasureCodingPolicyRequestProto{} }
func (m *SetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*SetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{0}
}

func (m *SetErasureCodingPolicyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetErasureCodingPolicyRequestProto.Unmarshal(m, b)
}
func (m *SetErasureCodingPolicyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetErasureCodingPolicyRequestProto.Marshal(b, m, deterministic)
}
func (m *SetErasureCodingPolicyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetErasureCodingPolicyRequestProto.Merge(m, src)
}
func (m *SetErasureCodingPolicyRequestProto) XXX_Size() int {
	return xxx_messageInfo_SetErasureCodingPolicyRequestProto.Size(m)
}
func (m *SetErasureCodingPolicyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SetErasureCodingPolicyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_SetErasureCodingPolicyRequestProto proto.InternalMessageInfo

func (m *SetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if m != nil && m.EcPolicyName != nil {
		return *m.EcPolicyName
	}
	return ""
}

type SetErasureCodingPolicyResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetErasureCodingPolicyResponseProto) Reset()         { *m = SetErasureCodingPolicyResponseProto{} }
func (m *SetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*SetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{1}
}

func (m *SetErasureCodingPolicyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetErasureCodingPolicyResponseProto.Unmarshal(m, b)
}
func (m *SetErasureCodingPolicyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetErasureCodingPolicyResponseProto.Marshal(b, m, deterministic)
}
func (m *SetErasureCodingPolicyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetErasureCodingPolicyResponseProto.Merge(m, src)
}
func (m *SetErasureCodingPolicyResponseProto) XXX_Size() int {
	return xxx_messageInfo_SetErasureCodingPolicyResponseProto.Size(m)
}
func (m *SetErasureCodingPolicyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SetErasureCodingPolicyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_SetErasureCodingPolicyResponseProto proto.InternalMessageInfo

type GetErasureCodingPoliciesRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetErasureCodingPoliciesRequestProto) Reset()         { *m = GetErasureCodingPoliciesRequestProto{} }
func (m *GetErasureCodingPoliciesRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPoliciesRequestProto) ProtoMessage()    {}
func (*GetErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{2}
}

func (m *GetErasureCodingPoliciesRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetErasureCodingPoliciesRequestProto.Unmarshal(m, b)
}
func (m *GetErasureCodingPoliciesRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetErasureCodingPoliciesRequestProto.Marshal(b, m, deterministic)
}
func (m *GetErasureCodingPoliciesRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetErasureCodingPoliciesRequestProto.Merge(m, src)
}
func (m *GetErasureCodingPoliciesRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetErasureCodingPoliciesRequestProto.Size(m)
}
func (m *GetErasureCodingPoliciesRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetErasureCodingPoliciesRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetErasureCodingPoliciesRequestProto proto.InternalMessageInfo

type GetErasureCodingPoliciesResponseProto struct {
	EcPolicies           []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetErasureCodingPoliciesResponseProto) Reset()         { *m = GetErasureCodingPoliciesResponseProto{} }
func (m *GetErasureCodingPoliciesResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPoliciesResponseProto) ProtoMessage()    {}
func (*GetErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{3}
}

func (m *GetErasureCodingPoliciesResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetErasureCodingPoliciesResponseProto.Unmarshal(m, b)
}
func (m *GetErasureCodingPoliciesResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetErasureCodingPoliciesResponseProto.Marshal(b, m, deterministic)
}
func (m *GetErasureCodingPoliciesResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetErasureCodingPoliciesResponseProto.Merge(m, src)
}
func (m *GetErasureCodingPoliciesResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetErasureCodingPoliciesResponseProto.Size(m)
}
func (m *GetErasureCodingPoliciesResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetErasureCodingPoliciesResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetErasureCodingPoliciesResponseProto proto.InternalMessageInfo

func (m *GetErasureCodingPoliciesResponseProto) GetEcPolicies() []*ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicies
	}
	return nil
}

type GetErasureCodingCodecsRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetErasureCodingCodecsRequestProto) Reset()         { *m = GetErasureCodingCodecsRequestProto{} }
func (m *GetErasureCodingCodecsRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingCodecsRequestProto) ProtoMessage()    {}
func (*GetErasureCodingCodecsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{4}
}

func (m *GetErasureCodingCodecsRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetErasureCodingCodecsRequestProto.Unmarshal(m, b)
}
func (m *GetErasureCodingCodecsRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetErasureCodingCodecsRequestProto.Marshal(b, m, deterministic)
}
func (m *GetErasureCodingCodecsRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetErasureCodingCodecsRequestProto.Merge(m, src)
}
func (m *GetErasureCodingCodecsRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetErasureCodingCodecsRequestProto.Size(m)
}
func (m *GetErasureCodingCodecsRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetErasureCodingCodecsRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetErasureCodingCodecsRequestProto proto.InternalMessageInfo

type GetErasureCodingCodecsResponseProto struct {
	Codec                []*CodecProto `protobuf:"bytes,1,rep,name=codec" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetErasureCodingCodecsResponseProto) Reset()         { *m = GetErasureCodingCodecsResponseProto{} }
func (m *GetErasureCodingCodecsResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingCodecsResponseProto) ProtoMessage()    {}
func (*GetErasureCodingCodecsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{5}
}

func (m *GetErasureCodingCodecsResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetErasureCodingCodecsResponseProto.Unmarshal(m, b)
}
func (m *GetErasureCodingCodecsResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetErasureCodingCodecsResponseProto.Marshal(b, m, deterministic)
}
func (m *GetErasureCodingCodecsResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetErasureCodingCodecsResponseProto.Merge(m, src)
}
func (m *GetErasureCodingCodecsResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetErasureCodingCodecsResponseProto.Size(m)
}
func (m *GetErasureCodingCodecsResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetErasureCodingCodecsResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetErasureCodingCodecsResponseProto proto.InternalMessageInfo

func (m *GetErasureCodingCodecsResponseProto) GetCodec() []*CodecProto {
	if m != nil {
		return m.Codec
	}
	return nil
}

type GetErasureCodingPolicyRequestProto struct {
	Src                  *string  `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetErasureCodingPolicyRequestProto) Reset()         { *m = GetErasureCodingPolicyRequestProto{} }
func (m *GetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*GetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{6}
}

func (m *GetErasureCodingPolicyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetErasureCodingPolicyRequestProto.Unmarshal(m, b)
}
func (m *GetErasureCodingPolicyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetErasureCodingPolicyRequestProto.Marshal(b, m, deterministic)
}
func (m *GetErasureCodingPolicyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetErasureCodingPolicyRequestProto.Merge(m, src)
}
func (m *GetErasureCodingPolicyRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetErasureCodingPolicyRequestProto.Size(m)
}
func (m *GetErasureCodingPolicyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetErasureCodingPolicyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetErasureCodingPolicyRequestProto proto.InternalMessageInfo

func (m *GetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetErasureCodingPolicyResponseProto struct {
	EcPolicy             *ErasureCodingPolicyProto `protobuf:"bytes,1,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetErasureCodingPolicyResponseProto) Reset()         { *m = GetErasureCodingPolicyResponseProto{} }
func (m *GetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*GetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{7}
}

func (m *GetErasureCodingPolicyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetErasureCodingPolicyResponseProto.Unmarshal(m, b)
}
func (m *GetErasureCodingPolicyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetErasureCodingPolicyResponseProto.Marshal(b, m, deterministic)
}
func (m *GetErasureCodingPolicyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetErasureCodingPolicyResponseProto.Merge(m, src)
}
func (m *GetErasureCodingPolicyResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetErasureCodingPolicyResponseProto.Size(m)
}
func (m *GetErasureCodingPolicyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetErasureCodingPolicyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetErasureCodingPolicyResponseProto proto.InternalMessageInfo

func (m *GetErasureCodingPolicyResponseProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

type AddErasureCodingPoliciesRequestProto struct {
	EcPolicies           []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AddErasureCodingPoliciesRequestProto) Reset()         { *m = AddErasureCodingPoliciesRequestProto{} }
func (m *AddErasureCodingPoliciesRequestProto) String() string { return proto.CompactTextString(m) }
func (*AddErasureCodingPoliciesRequestProto) ProtoMessage()    {}
func (*AddErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{8}
}

func (m *AddErasureCodingPoliciesRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddErasureCodingPoliciesRequestProto.Unmarshal(m, b)
}
func (m *AddErasureCodingPoliciesRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddErasureCodingPoliciesRequestProto.Marshal(b, m, deterministic)
}
func (m *AddErasureCodingPoliciesRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddErasureCodingPoliciesRequestProto.Merge(m, src)
}
func (m *AddErasureCodingPoliciesRequestProto) XXX_Size() int {
	return xxx_messageInfo_AddErasureCodingPoliciesRequestProto.Size(m)
}
func (m *AddErasureCodingPoliciesRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AddErasureCodingPoliciesRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_AddErasureCodingPoliciesRequestProto proto.InternalMessageInfo

func (m *AddErasureCodingPoliciesRequestProto) GetEcPolicies() []*ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicies
	}
	return nil
}

type AddErasureCodingPoliciesResponseProto struct {
	Responses            []*AddErasureCodingPolicyResponseProto `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *AddErasureCodingPoliciesResponseProto) Reset()         { *m = AddErasureCodingPoliciesResponseProto{} }
func (m *AddErasureCodingPoliciesResponseProto) String() string { return proto.CompactTextString(m) }
func (*AddErasureCodingPoliciesResponseProto) ProtoMessage()    {}
func (*AddErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{9}
}

func (m *AddErasureCodingPoliciesResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddErasureCodingPoliciesResponseProto.Unmarshal(m, b)
}
func (m *AddErasureCodingPoliciesResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddErasureCodingPoliciesResponseProto.Marshal(b, m, deterministic)
}
func (m *AddErasureCodingPoliciesResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddErasureCodingPoliciesResponseProto.Merge(m, src)
}
func (m *AddErasureCodingPoliciesResponseProto) XXX_Size() int {
	return xxx_messageInfo_AddErasureCodingPoliciesResponseProto.Size(m)
}
func (m *AddErasureCodingPoliciesResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AddErasureCodingPoliciesResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_AddErasureCodingPoliciesResponseProto proto.InternalMessageInfo

func (m *AddErasureCodingPoliciesResponseProto) GetResponses() []*AddErasureCodingPolicyResponseProto {
	if m != nil {
		return m.Responses
	}
	return nil
}

type RemoveErasureCodingPolicyRequestProto struct {
	EcPolicyName         *string  `protobuf:"bytes,1,req,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveErasureCodingPolicyRequestProto) Reset()         { *m = RemoveErasureCodingPolicyRequestProto{} }
func (m *RemoveErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*RemoveErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*RemoveErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{10}
}

func (m *RemoveErasureCodingPolicyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveErasureCodingPolicyRequestProto.Unmarshal(m, b)
}
func (m *RemoveErasureCodingPolicyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveErasureCodingPolicyRequestProto.Marshal(b, m, deterministic)
}
func (m *RemoveErasureCodingPolicyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveErasureCodingPolicyRequestProto.Merge(m, src)
}
func (m *RemoveErasureCodingPolicyRequestProto) XXX_Size() int {
	return xxx_messageInfo_RemoveErasureCodingPolicyRequestProto.Size(m)
}
func (m *RemoveErasureCodingPolicyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveErasureCodingPolicyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveErasureCodingPolicyRequestProto proto.InternalMessageInfo

func (m *RemoveErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if m != nil && m.EcPolicyName != nil {
		return *m.EcPolicyName
	}
	return ""
}

type RemoveErasureCodingPolicyResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveErasureCodingPolicyResponseProto) Reset() {
	*m = RemoveErasureCodingPolicyResponseProto{}
}
func (m *RemoveErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*RemoveErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*RemoveErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{11}
}

func (m *RemoveErasureCodingPolicyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveErasureCodingPolicyResponseProto.Unmarshal(m, b)
}
func (m *RemoveErasureCodingPolicyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveErasureCodingPolicyResponseProto.Marshal(b, m, deterministic)
}
func (m *RemoveErasureCodingPolicyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveErasureCodingPolicyResponseProto.Merge(m, src)
}
func (m *RemoveErasureCodingPolicyResponseProto) XXX_Size() int {
	return xxx_messageInfo_RemoveErasureCodingPolicyResponseProto.Size(m)
}
func (m *RemoveErasureCodingPolicyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveErasureCodingPolicyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveErasureCodingPolicyResponseProto proto.InternalMessageInfo

type EnableErasureCodingPolicyRequestProto struct {
	EcPolicyName         *string  `protobuf:"bytes,1,req,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableErasureCodingPolicyRequestProto) Reset()         { *m = EnableErasureCodingPolicyRequestProto{} }
func (m *EnableErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*EnableErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*EnableErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{12}
}

func (m *EnableErasureCodingPolicyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableErasureCodingPolicyRequestProto.Unmarshal(m, b)
}
func (m *EnableErasureCodingPolicyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableErasureCodingPolicyRequestProto.Marshal(b, m, deterministic)
}
func (m *EnableErasureCodingPolicyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableErasureCodingPolicyRequestProto.Merge(m, src)
}
func (m *EnableErasureCodingPolicyRequestProto) XXX_Size() int {
	return xxx_messageInfo_EnableErasureCodingPolicyRequestProto.Size(m)
}
func (m *EnableErasureCodingPolicyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableErasureCodingPolicyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_EnableErasureCodingPolicyRequestProto proto.InternalMessageInfo

func (m *EnableErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if m != nil && m.EcPolicyName != nil {
		return *m.EcPolicyName
	}
	return ""
}

type EnableErasureCodingPolicyResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableErasureCodingPolicyResponseProto) Reset() {
	*m = EnableErasureCodingPolicyResponseProto{}
}
func (m *EnableErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*EnableErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*EnableErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{13}
}

func (m *EnableErasureCodingPolicyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableErasureCodingPolicyResponseProto.Unmarshal(m, b)
}
func (m *EnableErasureCodingPolicyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableErasureCodingPolicyResponseProto.Marshal(b, m, deterministic)
}
func (m *EnableErasureCodingPolicyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableErasureCodingPolicyResponseProto.Merge(m, src)
}
func (m *EnableErasureCodingPolicyResponseProto) XXX_Size() int {
	return xxx_messageInfo_EnableErasureCodingPolicyResponseProto.Size(m)
}
func (m *EnableErasureCodingPolicyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableErasureCodingPolicyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_EnableErasureCodingPolicyResponseProto proto.InternalMessageInfo

type DisableErasureCodingPolicyRequestProto struct {
	EcPolicyName         *string  `protobuf:"bytes,1,req,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableErasureCodingPolicyRequestProto) Reset() {
	*m = DisableErasureCodingPolicyRequestProto{}
}
func (m *DisableErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*DisableErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*DisableErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{14}
}

func (m *DisableErasureCodingPolicyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableErasureCodingPolicyRequestProto.Unmarshal(m, b)
}
func (m *DisableErasureCodingPolicyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableErasureCodingPolicyRequestProto.Marshal(b, m, deterministic)
}
func (m *DisableErasureCodingPolicyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableErasureCodingPolicyRequestProto.Merge(m, src)
}
func (m *DisableErasureCodingPolicyRequestProto) XXX_Size() int {
	return xxx_messageInfo_DisableErasureCodingPolicyRequestProto.Size(m)
}
func (m *DisableErasureCodingPolicyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableErasureCodingPolicyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_DisableErasureCodingPolicyRequestProto proto.InternalMessageInfo

func (m *DisableErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if m != nil && m.EcPolicyName != nil {
		return *m.EcPolicyName
	}
	return ""
}

type DisableErasureCodingPolicyResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableErasureCodingPolicyResponseProto) Reset() {
	*m = DisableErasureCodingPolicyResponseProto{}
}
func (m *DisableErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*DisableErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*DisableErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{15}
}

func (m *DisableErasureCodingPolicyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableErasureCodingPolicyResponseProto.Unmarshal(m, b)
}
func (m *DisableErasureCodingPolicyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableErasureCodingPolicyResponseProto.Marshal(b, m, deterministic)
}
func (m *DisableErasureCodingPolicyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableErasureCodingPolicyResponseProto.Merge(m, src)
}
func (m *DisableErasureCodingPolicyResponseProto) XXX_Size() int {
	return xxx_messageInfo_DisableErasureCodingPolicyResponseProto.Size(m)
}
func (m *DisableErasureCodingPolicyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableErasureCodingPolicyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_DisableErasureCodingPolicyResponseProto proto.InternalMessageInfo

type UnsetErasureCodingPolicyRequestProto struct {
	Src                  *string  `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsetErasureCodingPolicyRequestProto) Reset()         { *m = UnsetErasureCodingPolicyRequestProto{} }
func (m *UnsetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*UnsetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*UnsetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{16}
}

func (m *UnsetErasureCodingPolicyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsetErasureCodingPolicyRequestProto.Unmarshal(m, b)
}
func (m *UnsetErasureCodingPolicyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsetErasureCodingPolicyRequestProto.Marshal(b, m, deterministic)
}
func (m *UnsetErasureCodingPolicyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsetErasureCodingPolicyRequestProto.Merge(m, src)
}
func (m *UnsetErasureCodingPolicyRequestProto) XXX_Size() int {
	return xxx_messageInfo_UnsetErasureCodingPolicyRequestProto.Size(m)
}
func (m *UnsetErasureCodingPolicyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsetErasureCodingPolicyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_UnsetErasureCodingPolicyRequestProto proto.InternalMessageInfo

func (m *UnsetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type UnsetErasureCodingPolicyResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsetErasureCodingPolicyResponseProto) Reset()         { *m = UnsetErasureCodingPolicyResponseProto{} }
func (m *UnsetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*UnsetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*UnsetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{17}
}

func (m *UnsetErasureCodingPolicyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsetErasureCodingPolicyResponseProto.Unmarshal(m, b)
}
func (m *UnsetErasureCodingPolicyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsetErasureCodingPolicyResponseProto.Marshal(b, m, deterministic)
}
func (m *UnsetErasureCodingPolicyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsetErasureCodingPolicyResponseProto.Merge(m, src)
}
func (m *UnsetErasureCodingPolicyResponseProto) XXX_Size() int {
	return xxx_messageInfo_UnsetErasureCodingPolicyResponseProto.Size(m)
}
func (m *UnsetErasureCodingPolicyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsetErasureCodingPolicyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_UnsetErasureCodingPolicyResponseProto proto.InternalMessageInfo

//*
// Block erasure coding reconstruction info
type BlockECReconstructionInfoProto struct {
	Block                *ExtendedBlockProto       `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	SourceDnInfos        *DatanodeInfosProto       `protobuf:"bytes,2,req,name=sourceDnInfos" json:"sourceDnInfos,omitempty"`
	TargetDnInfos        *DatanodeInfosProto       `protobuf:"bytes,3,req,name=targetDnInfos" json:"targetDnInfos,omitempty"`
	TargetStorageUuids   *StorageUuidsProto        `protobuf:"bytes,4,req,name=targetStorageUuids" json:"targetStorageUuids,omitempty"`
	TargetStorageTypes   *StorageTypesProto        `protobuf:"bytes,5,req,name=targetStorageTypes" json:"targetStorageTypes,omitempty"`
	LiveBlockIndices     []byte                    `protobuf:"bytes,6,req,name=liveBlockIndices" json:"liveBlockIndices,omitempty"`
	EcPolicy             *ErasureCodingPolicyProto `protobuf:"bytes,7,req,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BlockECReconstructionInfoProto) Reset()         { *m = BlockECReconstructionInfoProto{} }
func (m *BlockECReconstructionInfoProto) String() string { return proto.CompactTextString(m) }
func (*BlockECReconstructionInfoProto) ProtoMessage()    {}
func (*BlockECReconstructionInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{18}
}

func (m *BlockECReconstructionInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockECReconstructionInfoProto.Unmarshal(m, b)
}
func (m *BlockECReconstructionInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockECReconstructionInfoProto.Marshal(b, m, deterministic)
}
func (m *BlockECReconstructionInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockECReconstructionInfoProto.Merge(m, src)
}
func (m *BlockECReconstructionInfoProto) XXX_Size() int {
	return xxx_messageInfo_BlockECReconstructionInfoProto.Size(m)
}
func (m *BlockECReconstructionInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockECReconstructionInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockECReconstructionInfoProto proto.InternalMessageInfo

func (m *BlockECReconstructionInfoProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetSourceDnInfos() *DatanodeInfosProto {
	if m != nil {
		return m.SourceDnInfos
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetDnInfos() *DatanodeInfosProto {
	if m != nil {
		return m.TargetDnInfos
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetStorageUuids() *StorageUuidsProto {
	if m != nil {
		return m.TargetStorageUuids
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetStorageTypes() *StorageTypesProto {
	if m != nil {
		return m.TargetStorageTypes
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetLiveBlockIndices() []byte {
	if m != nil {
		return m.LiveBlockIndices
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

//*
// Codec and it's corresponding coders
type CodecProto struct {
	Codec                *string  `protobuf:"bytes,1,req,name=codec" json:"codec,omitempty"`
	Coders               *string  `protobuf:"bytes,2,req,name=coders" json:"coders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodecProto) Reset()         { *m = CodecProto{} }
func (m *CodecProto) String() string { return proto.CompactTextString(m) }
func (*CodecProto) ProtoMessage()    {}
func (*CodecProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c24b9abdd2ea6ec, []int{19}
}

func (m *CodecProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodecProto.Unmarshal(m, b)
}
func (m *CodecProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodecProto.Marshal(b, m, deterministic)
}
func (m *CodecProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodecProto.Merge(m, src)
}
func (m *CodecProto) XXX_Size() int {
	return xxx_messageInfo_CodecProto.Size(m)
}
func (m *CodecProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CodecProto.DiscardUnknown(m)
}

var xxx_messageInfo_CodecProto proto.InternalMessageInfo

func (m *CodecProto) GetCodec() string {
	if m != nil && m.Codec != nil {
		return *m.Codec
	}
	return ""
}

func (m *CodecProto) GetCoders() string {
	if m != nil && m.Coders != nil {
		return *m.Coders
	}
	return ""
}

func init() {
	proto.RegisterType((*SetErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.SetErasureCodingPolicyRequestProto")
	proto.RegisterType((*SetErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.SetErasureCodingPolicyResponseProto")
	proto.RegisterType((*GetErasureCodingPoliciesRequestProto)(nil), "hadoop.hdfs.GetErasureCodingPoliciesRequestProto")
	proto.RegisterType((*GetErasureCodingPoliciesResponseProto)(nil), "hadoop.hdfs.GetErasureCodingPoliciesResponseProto")
	proto.RegisterType((*GetErasureCodingCodecsRequestProto)(nil), "hadoop.hdfs.GetErasureCodingCodecsRequestProto")
	proto.RegisterType((*GetErasureCodingCodecsResponseProto)(nil), "hadoop.hdfs.GetErasureCodingCodecsResponseProto")
	proto.RegisterType((*GetErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.GetErasureCodingPolicyRequestProto")
	proto.RegisterType((*GetErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.GetErasureCodingPolicyResponseProto")
	proto.RegisterType((*AddErasureCodingPoliciesRequestProto)(nil), "hadoop.hdfs.AddErasureCodingPoliciesRequestProto")
	proto.RegisterType((*AddErasureCodingPoliciesResponseProto)(nil), "hadoop.hdfs.AddErasureCodingPoliciesResponseProto")
	proto.RegisterType((*RemoveErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.RemoveErasureCodingPolicyRequestProto")
	proto.RegisterType((*RemoveErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.RemoveErasureCodingPolicyResponseProto")
	proto.RegisterType((*EnableErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.EnableErasureCodingPolicyRequestProto")
	proto.RegisterType((*EnableErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.EnableErasureCodingPolicyResponseProto")
	proto.RegisterType((*DisableErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.DisableErasureCodingPolicyRequestProto")
	proto.RegisterType((*DisableErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.DisableErasureCodingPolicyResponseProto")
	proto.RegisterType((*UnsetErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.UnsetErasureCodingPolicyRequestProto")
	proto.RegisterType((*UnsetErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.UnsetErasureCodingPolicyResponseProto")
	proto.RegisterType((*BlockECReconstructionInfoProto)(nil), "hadoop.hdfs.BlockECReconstructionInfoProto")
	proto.RegisterType((*CodecProto)(nil), "hadoop.hdfs.CodecProto")
}

func init() { proto.RegisterFile("erasurecoding.proto", fileDescriptor_9c24b9abdd2ea6ec) }

var fileDescriptor_9c24b9abdd2ea6ec = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0x95, 0xf6, 0xed, 0x5e, 0x7a, 0x3a, 0xa4, 0x29, 0x43, 0x10, 0x71, 0x31, 0x2a, 0xaf,
	0xe9, 0x0a, 0x12, 0x15, 0x9a, 0x04, 0x42, 0xdc, 0xa0, 0xf5, 0x8f, 0xd0, 0x34, 0x54, 0x4d, 0xd9,
	0x76, 0xc3, 0x5d, 0x66, 0x9f, 0xb5, 0x11, 0xad, 0x5d, 0xec, 0x74, 0xb0, 0x6f, 0xc3, 0x87, 0xe4,
	0x03, 0xa0, 0xd8, 0x2d, 0xb5, 0xd7, 0xa4, 0x2b, 0xa8, 0x37, 0x95, 0x73, 0x72, 0x9e, 0xdf, 0x73,
	0x7a, 0x8e, 0xed, 0xc0, 0x3e, 0xca, 0x58, 0xcd, 0x24, 0x52, 0xc1, 0x12, 0x3e, 0x6c, 0x4f, 0xa5,
	0x48, 0x85, 0x5f, 0x1b, 0xc5, 0x4c, 0x88, 0x69, 0x7b, 0xc4, 0x6e, 0xd4, 0x73, 0xc8, 0x7e, 0xcd,
	0x0b, 0xf2, 0x05, 0xc8, 0x05, 0xa6, 0x7d, 0x23, 0xe9, 0x6a, 0xc9, 0xb9, 0x18, 0x27, 0xf4, 0x2e,
	0xc2, 0x6f, 0x33, 0x54, 0xe9, 0xb9, 0x96, 0xef, 0x41, 0x59, 0x49, 0x1a, 0x78, 0xf5, 0x52, 0xab,
	0x1a, 0x65, 0x4b, 0x9f, 0xc0, 0x2e, 0x52, 0x93, 0x39, 0x88, 0x27, 0x18, 0x94, 0xea, 0x5e, 0xab,
	0x1a, 0x39, 0x31, 0x12, 0xc2, 0x61, 0x11, 0x5b, 0x4d, 0x05, 0x57, 0xa8, 0xe1, 0xa4, 0x09, 0x8d,
	0x4f, 0x79, 0x69, 0x09, 0x2a, 0xbb, 0x08, 0xc2, 0x21, 0x2c, 0xce, 0xb3, 0x80, 0x7e, 0x1f, 0x60,
	0x5e, 0x47, 0x82, 0x2a, 0xf0, 0xea, 0xe5, 0x56, 0xed, 0x38, 0x6c, 0x5b, 0x1d, 0x68, 0xe7, 0xd4,
	0xa4, 0xa5, 0x91, 0x25, 0x24, 0x0d, 0x20, 0xf7, 0xfd, 0xba, 0x82, 0x21, 0x75, 0xab, 0xba, 0x84,
	0xc3, 0xa2, 0x2c, 0xbb, 0xa6, 0xd7, 0x50, 0xa1, 0x59, 0x78, 0x5e, 0xce, 0x33, 0xa7, 0x1c, 0x2d,
	0x30, 0x05, 0x98, 0x2c, 0xf2, 0x6e, 0xd5, 0x7b, 0x93, 0xb1, 0x90, 0xd1, 0x6a, 0x35, 0x39, 0x2d,
	0xf7, 0x4f, 0xe0, 0xd1, 0x62, 0x52, 0x81, 0x57, 0xf7, 0x36, 0xef, 0xcf, 0x1f, 0x19, 0x99, 0x40,
	0xe3, 0x84, 0xb1, 0x07, 0xa7, 0xb6, 0xad, 0x61, 0x7c, 0x87, 0xb0, 0xd8, 0xce, 0xfe, 0x6b, 0x03,
	0xa8, 0xca, 0x79, 0x60, 0x61, 0xf7, 0xc6, 0xb1, 0xcb, 0xc5, 0xb8, 0xfd, 0x89, 0x96, 0x08, 0x72,
	0x06, 0x61, 0x84, 0x13, 0x71, 0x8b, 0x0f, 0x0d, 0xe3, 0xfe, 0x89, 0x30, 0x53, 0x71, 0x4f, 0x44,
	0x0b, 0x9a, 0x6b, 0x60, 0xf6, 0xa1, 0x38, 0x83, 0xb0, 0xcf, 0xe3, 0xeb, 0xf1, 0xb6, 0x6c, 0xd7,
	0xc0, 0x6c, 0xdb, 0xcf, 0xd0, 0xec, 0x25, 0x6a, 0x5b, 0xbe, 0x2f, 0xe1, 0x68, 0x1d, 0xcd, 0x36,
	0x7e, 0x0f, 0x8d, 0x2b, 0xae, 0xfe, 0x65, 0xcb, 0x1f, 0x41, 0x58, 0xac, 0xb4, 0x2d, 0x7e, 0x95,
	0xe1, 0xa0, 0x33, 0x16, 0xf4, 0x6b, 0xbf, 0x1b, 0x21, 0x15, 0x5c, 0xa5, 0x72, 0x46, 0xd3, 0x44,
	0xf0, 0x53, 0x7e, 0x23, 0x0c, 0xfd, 0x2d, 0x54, 0xae, 0xb3, 0x0c, 0xcd, 0xaf, 0x1d, 0xbf, 0x70,
	0xf7, 0xe9, 0x8f, 0x14, 0x39, 0x43, 0xa6, 0x19, 0xf3, 0xd3, 0xaa, 0xb3, 0xfd, 0x3e, 0x3c, 0x56,
	0x62, 0x26, 0x29, 0xf6, 0x34, 0x4b, 0x05, 0xa5, 0x1c, 0x79, 0x2f, 0x4e, 0x63, 0x2e, 0x18, 0xea,
	0x0c, 0x23, 0x77, 0x55, 0x19, 0x26, 0x8d, 0xe5, 0x10, 0xd3, 0x05, 0xa6, 0xbc, 0x21, 0xc6, 0x51,
	0xf9, 0x03, 0xf0, 0x4d, 0xe0, 0x22, 0x15, 0x32, 0x1e, 0xe2, 0xd5, 0x2c, 0x61, 0x2a, 0xf8, 0x4f,
	0xb3, 0x0e, 0x1c, 0x96, 0x9d, 0x60, 0x50, 0x39, 0xca, 0x15, 0xde, 0xe5, 0xdd, 0x14, 0x55, 0x50,
	0x29, 0xe6, 0xe9, 0x84, 0x3c, 0x9e, 0x7e, 0xe1, 0xbf, 0x82, 0xbd, 0x71, 0x72, 0x8b, 0xba, 0x8d,
	0xa7, 0x9c, 0x25, 0x14, 0x55, 0xb0, 0x53, 0x2f, 0xb5, 0x76, 0xa3, 0x95, 0xb8, 0x73, 0x51, 0xfd,
	0xaf, 0x1d, 0xff, 0xfa, 0xa2, 0xfa, 0x00, 0xb0, 0xbc, 0x5f, 0xfd, 0x27, 0xcb, 0x7b, 0x38, 0xdb,
	0x41, 0xe6, 0xc1, 0x7f, 0x0a, 0x3b, 0xd9, 0x42, 0x9a, 0xc9, 0x55, 0xa3, 0xf9, 0x53, 0xe7, 0x23,
	0x84, 0x42, 0x0e, 0xdb, 0xf1, 0x34, 0xa6, 0x23, 0x74, 0x8c, 0xf5, 0xd7, 0x93, 0x8a, 0xb1, 0x59,
	0x74, 0xf6, 0xdd, 0x42, 0xb2, 0x98, 0xfa, 0xe9, 0x79, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8f,
	0xaa, 0x01, 0xbc, 0x8d, 0x07, 0x00, 0x00,
}
