// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RpcHeader.proto

package hadoop_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// RpcKind determine the rpcEngine and the serialization of the rpc request
type RpcKindProto int32

const (
	RpcKindProto_RPC_BUILTIN         RpcKindProto = 0
	RpcKindProto_RPC_WRITABLE        RpcKindProto = 1
	RpcKindProto_RPC_PROTOCOL_BUFFER RpcKindProto = 2
)

var RpcKindProto_name = map[int32]string{
	0: "RPC_BUILTIN",
	1: "RPC_WRITABLE",
	2: "RPC_PROTOCOL_BUFFER",
}

var RpcKindProto_value = map[string]int32{
	"RPC_BUILTIN":         0,
	"RPC_WRITABLE":        1,
	"RPC_PROTOCOL_BUFFER": 2,
}

func (x RpcKindProto) Enum() *RpcKindProto {
	p := new(RpcKindProto)
	*p = x
	return p
}

func (x RpcKindProto) String() string {
	return proto.EnumName(RpcKindProto_name, int32(x))
}

func (x *RpcKindProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpcKindProto_value, data, "RpcKindProto")
	if err != nil {
		return err
	}
	*x = RpcKindProto(value)
	return nil
}

func (RpcKindProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{0}
}

type RpcRequestHeaderProto_OperationProto int32

const (
	RpcRequestHeaderProto_RPC_FINAL_PACKET        RpcRequestHeaderProto_OperationProto = 0
	RpcRequestHeaderProto_RPC_CONTINUATION_PACKET RpcRequestHeaderProto_OperationProto = 1
	RpcRequestHeaderProto_RPC_CLOSE_CONNECTION    RpcRequestHeaderProto_OperationProto = 2
)

var RpcRequestHeaderProto_OperationProto_name = map[int32]string{
	0: "RPC_FINAL_PACKET",
	1: "RPC_CONTINUATION_PACKET",
	2: "RPC_CLOSE_CONNECTION",
}

var RpcRequestHeaderProto_OperationProto_value = map[string]int32{
	"RPC_FINAL_PACKET":        0,
	"RPC_CONTINUATION_PACKET": 1,
	"RPC_CLOSE_CONNECTION":    2,
}

func (x RpcRequestHeaderProto_OperationProto) Enum() *RpcRequestHeaderProto_OperationProto {
	p := new(RpcRequestHeaderProto_OperationProto)
	*p = x
	return p
}

func (x RpcRequestHeaderProto_OperationProto) String() string {
	return proto.EnumName(RpcRequestHeaderProto_OperationProto_name, int32(x))
}

func (x *RpcRequestHeaderProto_OperationProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpcRequestHeaderProto_OperationProto_value, data, "RpcRequestHeaderProto_OperationProto")
	if err != nil {
		return err
	}
	*x = RpcRequestHeaderProto_OperationProto(value)
	return nil
}

func (RpcRequestHeaderProto_OperationProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{2, 0}
}

type RpcResponseHeaderProto_RpcStatusProto int32

const (
	RpcResponseHeaderProto_SUCCESS RpcResponseHeaderProto_RpcStatusProto = 0
	RpcResponseHeaderProto_ERROR   RpcResponseHeaderProto_RpcStatusProto = 1
	RpcResponseHeaderProto_FATAL   RpcResponseHeaderProto_RpcStatusProto = 2
)

var RpcResponseHeaderProto_RpcStatusProto_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
	2: "FATAL",
}

var RpcResponseHeaderProto_RpcStatusProto_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
	"FATAL":   2,
}

func (x RpcResponseHeaderProto_RpcStatusProto) Enum() *RpcResponseHeaderProto_RpcStatusProto {
	p := new(RpcResponseHeaderProto_RpcStatusProto)
	*p = x
	return p
}

func (x RpcResponseHeaderProto_RpcStatusProto) String() string {
	return proto.EnumName(RpcResponseHeaderProto_RpcStatusProto_name, int32(x))
}

func (x *RpcResponseHeaderProto_RpcStatusProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpcResponseHeaderProto_RpcStatusProto_value, data, "RpcResponseHeaderProto_RpcStatusProto")
	if err != nil {
		return err
	}
	*x = RpcResponseHeaderProto_RpcStatusProto(value)
	return nil
}

func (RpcResponseHeaderProto_RpcStatusProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{3, 0}
}

type RpcResponseHeaderProto_RpcErrorCodeProto int32

const (
	// Non-fatal Rpc error - connection left open for future rpc calls
	RpcResponseHeaderProto_ERROR_APPLICATION          RpcResponseHeaderProto_RpcErrorCodeProto = 1
	RpcResponseHeaderProto_ERROR_NO_SUCH_METHOD       RpcResponseHeaderProto_RpcErrorCodeProto = 2
	RpcResponseHeaderProto_ERROR_NO_SUCH_PROTOCOL     RpcResponseHeaderProto_RpcErrorCodeProto = 3
	RpcResponseHeaderProto_ERROR_RPC_SERVER           RpcResponseHeaderProto_RpcErrorCodeProto = 4
	RpcResponseHeaderProto_ERROR_SERIALIZING_RESPONSE RpcResponseHeaderProto_RpcErrorCodeProto = 5
	RpcResponseHeaderProto_ERROR_RPC_VERSION_MISMATCH RpcResponseHeaderProto_RpcErrorCodeProto = 6
	// Fatal Server side Rpc error - connection closed
	RpcResponseHeaderProto_FATAL_UNKNOWN                   RpcResponseHeaderProto_RpcErrorCodeProto = 10
	RpcResponseHeaderProto_FATAL_UNSUPPORTED_SERIALIZATION RpcResponseHeaderProto_RpcErrorCodeProto = 11
	RpcResponseHeaderProto_FATAL_INVALID_RPC_HEADER        RpcResponseHeaderProto_RpcErrorCodeProto = 12
	RpcResponseHeaderProto_FATAL_DESERIALIZING_REQUEST     RpcResponseHeaderProto_RpcErrorCodeProto = 13
	RpcResponseHeaderProto_FATAL_VERSION_MISMATCH          RpcResponseHeaderProto_RpcErrorCodeProto = 14
	RpcResponseHeaderProto_FATAL_UNAUTHORIZED              RpcResponseHeaderProto_RpcErrorCodeProto = 15
)

var RpcResponseHeaderProto_RpcErrorCodeProto_name = map[int32]string{
	1:  "ERROR_APPLICATION",
	2:  "ERROR_NO_SUCH_METHOD",
	3:  "ERROR_NO_SUCH_PROTOCOL",
	4:  "ERROR_RPC_SERVER",
	5:  "ERROR_SERIALIZING_RESPONSE",
	6:  "ERROR_RPC_VERSION_MISMATCH",
	10: "FATAL_UNKNOWN",
	11: "FATAL_UNSUPPORTED_SERIALIZATION",
	12: "FATAL_INVALID_RPC_HEADER",
	13: "FATAL_DESERIALIZING_REQUEST",
	14: "FATAL_VERSION_MISMATCH",
	15: "FATAL_UNAUTHORIZED",
}

var RpcResponseHeaderProto_RpcErrorCodeProto_value = map[string]int32{
	"ERROR_APPLICATION":               1,
	"ERROR_NO_SUCH_METHOD":            2,
	"ERROR_NO_SUCH_PROTOCOL":          3,
	"ERROR_RPC_SERVER":                4,
	"ERROR_SERIALIZING_RESPONSE":      5,
	"ERROR_RPC_VERSION_MISMATCH":      6,
	"FATAL_UNKNOWN":                   10,
	"FATAL_UNSUPPORTED_SERIALIZATION": 11,
	"FATAL_INVALID_RPC_HEADER":        12,
	"FATAL_DESERIALIZING_REQUEST":     13,
	"FATAL_VERSION_MISMATCH":          14,
	"FATAL_UNAUTHORIZED":              15,
}

func (x RpcResponseHeaderProto_RpcErrorCodeProto) Enum() *RpcResponseHeaderProto_RpcErrorCodeProto {
	p := new(RpcResponseHeaderProto_RpcErrorCodeProto)
	*p = x
	return p
}

func (x RpcResponseHeaderProto_RpcErrorCodeProto) String() string {
	return proto.EnumName(RpcResponseHeaderProto_RpcErrorCodeProto_name, int32(x))
}

func (x *RpcResponseHeaderProto_RpcErrorCodeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpcResponseHeaderProto_RpcErrorCodeProto_value, data, "RpcResponseHeaderProto_RpcErrorCodeProto")
	if err != nil {
		return err
	}
	*x = RpcResponseHeaderProto_RpcErrorCodeProto(value)
	return nil
}

func (RpcResponseHeaderProto_RpcErrorCodeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{3, 1}
}

type RpcSaslProto_SaslState int32

const (
	RpcSaslProto_SUCCESS   RpcSaslProto_SaslState = 0
	RpcSaslProto_NEGOTIATE RpcSaslProto_SaslState = 1
	RpcSaslProto_INITIATE  RpcSaslProto_SaslState = 2
	RpcSaslProto_CHALLENGE RpcSaslProto_SaslState = 3
	RpcSaslProto_RESPONSE  RpcSaslProto_SaslState = 4
	RpcSaslProto_WRAP      RpcSaslProto_SaslState = 5
)

var RpcSaslProto_SaslState_name = map[int32]string{
	0: "SUCCESS",
	1: "NEGOTIATE",
	2: "INITIATE",
	3: "CHALLENGE",
	4: "RESPONSE",
	5: "WRAP",
}

var RpcSaslProto_SaslState_value = map[string]int32{
	"SUCCESS":   0,
	"NEGOTIATE": 1,
	"INITIATE":  2,
	"CHALLENGE": 3,
	"RESPONSE":  4,
	"WRAP":      5,
}

func (x RpcSaslProto_SaslState) Enum() *RpcSaslProto_SaslState {
	p := new(RpcSaslProto_SaslState)
	*p = x
	return p
}

func (x RpcSaslProto_SaslState) String() string {
	return proto.EnumName(RpcSaslProto_SaslState_name, int32(x))
}

func (x *RpcSaslProto_SaslState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpcSaslProto_SaslState_value, data, "RpcSaslProto_SaslState")
	if err != nil {
		return err
	}
	*x = RpcSaslProto_SaslState(value)
	return nil
}

func (RpcSaslProto_SaslState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{4, 0}
}

//*
// Used to pass through the information necessary to continue
// a trace after an RPC is made. All we need is the traceid
// (so we know the overarching trace this message is a part of), and
// the id of the current span when this message was sent, so we know
// what span caused the new span we will create when this message is received.
type RPCTraceInfoProto struct {
	TraceId              *int64   `protobuf:"varint,1,opt,name=traceId" json:"traceId,omitempty"`
	ParentId             *int64   `protobuf:"varint,2,opt,name=parentId" json:"parentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCTraceInfoProto) Reset()         { *m = RPCTraceInfoProto{} }
func (m *RPCTraceInfoProto) String() string { return proto.CompactTextString(m) }
func (*RPCTraceInfoProto) ProtoMessage()    {}
func (*RPCTraceInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{0}
}

func (m *RPCTraceInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCTraceInfoProto.Unmarshal(m, b)
}
func (m *RPCTraceInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCTraceInfoProto.Marshal(b, m, deterministic)
}
func (m *RPCTraceInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCTraceInfoProto.Merge(m, src)
}
func (m *RPCTraceInfoProto) XXX_Size() int {
	return xxx_messageInfo_RPCTraceInfoProto.Size(m)
}
func (m *RPCTraceInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCTraceInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_RPCTraceInfoProto proto.InternalMessageInfo

func (m *RPCTraceInfoProto) GetTraceId() int64 {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return 0
}

func (m *RPCTraceInfoProto) GetParentId() int64 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

//*
// Used to pass through the call context entry after an RPC is made.
type RPCCallerContextProto struct {
	Context              *string  `protobuf:"bytes,1,req,name=context" json:"context,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCCallerContextProto) Reset()         { *m = RPCCallerContextProto{} }
func (m *RPCCallerContextProto) String() string { return proto.CompactTextString(m) }
func (*RPCCallerContextProto) ProtoMessage()    {}
func (*RPCCallerContextProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{1}
}

func (m *RPCCallerContextProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCCallerContextProto.Unmarshal(m, b)
}
func (m *RPCCallerContextProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCCallerContextProto.Marshal(b, m, deterministic)
}
func (m *RPCCallerContextProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCCallerContextProto.Merge(m, src)
}
func (m *RPCCallerContextProto) XXX_Size() int {
	return xxx_messageInfo_RPCCallerContextProto.Size(m)
}
func (m *RPCCallerContextProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCCallerContextProto.DiscardUnknown(m)
}

var xxx_messageInfo_RPCCallerContextProto proto.InternalMessageInfo

func (m *RPCCallerContextProto) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

func (m *RPCCallerContextProto) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RpcRequestHeaderProto struct {
	RpcKind  *RpcKindProto                         `protobuf:"varint,1,opt,name=rpcKind,enum=hadoop.common.RpcKindProto" json:"rpcKind,omitempty"`
	RpcOp    *RpcRequestHeaderProto_OperationProto `protobuf:"varint,2,opt,name=rpcOp,enum=hadoop.common.RpcRequestHeaderProto_OperationProto" json:"rpcOp,omitempty"`
	CallId   *int32                                `protobuf:"zigzag32,3,req,name=callId" json:"callId,omitempty"`
	ClientId []byte                                `protobuf:"bytes,4,req,name=clientId" json:"clientId,omitempty"`
	// clientId + callId uniquely identifies a request
	// retry count, 1 means this is the first retry
	RetryCount           *int32                 `protobuf:"zigzag32,5,opt,name=retryCount,def=-1" json:"retryCount,omitempty"`
	TraceInfo            *RPCTraceInfoProto     `protobuf:"bytes,6,opt,name=traceInfo" json:"traceInfo,omitempty"`
	CallerContext        *RPCCallerContextProto `protobuf:"bytes,7,opt,name=callerContext" json:"callerContext,omitempty"`
	StateId              *int64                 `protobuf:"varint,8,opt,name=stateId" json:"stateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RpcRequestHeaderProto) Reset()         { *m = RpcRequestHeaderProto{} }
func (m *RpcRequestHeaderProto) String() string { return proto.CompactTextString(m) }
func (*RpcRequestHeaderProto) ProtoMessage()    {}
func (*RpcRequestHeaderProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{2}
}

func (m *RpcRequestHeaderProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRequestHeaderProto.Unmarshal(m, b)
}
func (m *RpcRequestHeaderProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRequestHeaderProto.Marshal(b, m, deterministic)
}
func (m *RpcRequestHeaderProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRequestHeaderProto.Merge(m, src)
}
func (m *RpcRequestHeaderProto) XXX_Size() int {
	return xxx_messageInfo_RpcRequestHeaderProto.Size(m)
}
func (m *RpcRequestHeaderProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRequestHeaderProto.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRequestHeaderProto proto.InternalMessageInfo

const Default_RpcRequestHeaderProto_RetryCount int32 = -1

func (m *RpcRequestHeaderProto) GetRpcKind() RpcKindProto {
	if m != nil && m.RpcKind != nil {
		return *m.RpcKind
	}
	return RpcKindProto_RPC_BUILTIN
}

func (m *RpcRequestHeaderProto) GetRpcOp() RpcRequestHeaderProto_OperationProto {
	if m != nil && m.RpcOp != nil {
		return *m.RpcOp
	}
	return RpcRequestHeaderProto_RPC_FINAL_PACKET
}

func (m *RpcRequestHeaderProto) GetCallId() int32 {
	if m != nil && m.CallId != nil {
		return *m.CallId
	}
	return 0
}

func (m *RpcRequestHeaderProto) GetClientId() []byte {
	if m != nil {
		return m.ClientId
	}
	return nil
}

func (m *RpcRequestHeaderProto) GetRetryCount() int32 {
	if m != nil && m.RetryCount != nil {
		return *m.RetryCount
	}
	return Default_RpcRequestHeaderProto_RetryCount
}

func (m *RpcRequestHeaderProto) GetTraceInfo() *RPCTraceInfoProto {
	if m != nil {
		return m.TraceInfo
	}
	return nil
}

func (m *RpcRequestHeaderProto) GetCallerContext() *RPCCallerContextProto {
	if m != nil {
		return m.CallerContext
	}
	return nil
}

func (m *RpcRequestHeaderProto) GetStateId() int64 {
	if m != nil && m.StateId != nil {
		return *m.StateId
	}
	return 0
}

//*
// Rpc Response Header
// +------------------------------------------------------------------+
// | Rpc total response length in bytes (4 bytes int)                 |
// |  (sum of next two parts)                                         |
// +------------------------------------------------------------------+
// | RpcResponseHeaderProto - serialized delimited ie has len         |
// +------------------------------------------------------------------+
// | if request is successful:                                        |
// |   - RpcResponse -  The actual rpc response  bytes follow         |
// |     the response header                                          |
// |     This response is serialized based on RpcKindProto            |
// | if request fails :                                               |
// |   The rpc response header contains the necessary info            |
// +------------------------------------------------------------------+
//
// Note that rpc response header is also used when connection setup fails.
// Ie the response looks like a rpc response with a fake callId.
type RpcResponseHeaderProto struct {
	CallId               *uint32                                   `protobuf:"varint,1,req,name=callId" json:"callId,omitempty"`
	Status               *RpcResponseHeaderProto_RpcStatusProto    `protobuf:"varint,2,req,name=status,enum=hadoop.common.RpcResponseHeaderProto_RpcStatusProto" json:"status,omitempty"`
	ServerIpcVersionNum  *uint32                                   `protobuf:"varint,3,opt,name=serverIpcVersionNum" json:"serverIpcVersionNum,omitempty"`
	ExceptionClassName   *string                                   `protobuf:"bytes,4,opt,name=exceptionClassName" json:"exceptionClassName,omitempty"`
	ErrorMsg             *string                                   `protobuf:"bytes,5,opt,name=errorMsg" json:"errorMsg,omitempty"`
	ErrorDetail          *RpcResponseHeaderProto_RpcErrorCodeProto `protobuf:"varint,6,opt,name=errorDetail,enum=hadoop.common.RpcResponseHeaderProto_RpcErrorCodeProto" json:"errorDetail,omitempty"`
	ClientId             []byte                                    `protobuf:"bytes,7,opt,name=clientId" json:"clientId,omitempty"`
	RetryCount           *int32                                    `protobuf:"zigzag32,8,opt,name=retryCount,def=-1" json:"retryCount,omitempty"`
	StateId              *int64                                    `protobuf:"varint,9,opt,name=stateId" json:"stateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *RpcResponseHeaderProto) Reset()         { *m = RpcResponseHeaderProto{} }
func (m *RpcResponseHeaderProto) String() string { return proto.CompactTextString(m) }
func (*RpcResponseHeaderProto) ProtoMessage()    {}
func (*RpcResponseHeaderProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{3}
}

func (m *RpcResponseHeaderProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResponseHeaderProto.Unmarshal(m, b)
}
func (m *RpcResponseHeaderProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResponseHeaderProto.Marshal(b, m, deterministic)
}
func (m *RpcResponseHeaderProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResponseHeaderProto.Merge(m, src)
}
func (m *RpcResponseHeaderProto) XXX_Size() int {
	return xxx_messageInfo_RpcResponseHeaderProto.Size(m)
}
func (m *RpcResponseHeaderProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResponseHeaderProto.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResponseHeaderProto proto.InternalMessageInfo

const Default_RpcResponseHeaderProto_RetryCount int32 = -1

func (m *RpcResponseHeaderProto) GetCallId() uint32 {
	if m != nil && m.CallId != nil {
		return *m.CallId
	}
	return 0
}

func (m *RpcResponseHeaderProto) GetStatus() RpcResponseHeaderProto_RpcStatusProto {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return RpcResponseHeaderProto_SUCCESS
}

func (m *RpcResponseHeaderProto) GetServerIpcVersionNum() uint32 {
	if m != nil && m.ServerIpcVersionNum != nil {
		return *m.ServerIpcVersionNum
	}
	return 0
}

func (m *RpcResponseHeaderProto) GetExceptionClassName() string {
	if m != nil && m.ExceptionClassName != nil {
		return *m.ExceptionClassName
	}
	return ""
}

func (m *RpcResponseHeaderProto) GetErrorMsg() string {
	if m != nil && m.ErrorMsg != nil {
		return *m.ErrorMsg
	}
	return ""
}

func (m *RpcResponseHeaderProto) GetErrorDetail() RpcResponseHeaderProto_RpcErrorCodeProto {
	if m != nil && m.ErrorDetail != nil {
		return *m.ErrorDetail
	}
	return RpcResponseHeaderProto_ERROR_APPLICATION
}

func (m *RpcResponseHeaderProto) GetClientId() []byte {
	if m != nil {
		return m.ClientId
	}
	return nil
}

func (m *RpcResponseHeaderProto) GetRetryCount() int32 {
	if m != nil && m.RetryCount != nil {
		return *m.RetryCount
	}
	return Default_RpcResponseHeaderProto_RetryCount
}

func (m *RpcResponseHeaderProto) GetStateId() int64 {
	if m != nil && m.StateId != nil {
		return *m.StateId
	}
	return 0
}

type RpcSaslProto struct {
	Version              *uint32                  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	State                *RpcSaslProto_SaslState  `protobuf:"varint,2,req,name=state,enum=hadoop.common.RpcSaslProto_SaslState" json:"state,omitempty"`
	Token                []byte                   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Auths                []*RpcSaslProto_SaslAuth `protobuf:"bytes,4,rep,name=auths" json:"auths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RpcSaslProto) Reset()         { *m = RpcSaslProto{} }
func (m *RpcSaslProto) String() string { return proto.CompactTextString(m) }
func (*RpcSaslProto) ProtoMessage()    {}
func (*RpcSaslProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{4}
}

func (m *RpcSaslProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSaslProto.Unmarshal(m, b)
}
func (m *RpcSaslProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSaslProto.Marshal(b, m, deterministic)
}
func (m *RpcSaslProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSaslProto.Merge(m, src)
}
func (m *RpcSaslProto) XXX_Size() int {
	return xxx_messageInfo_RpcSaslProto.Size(m)
}
func (m *RpcSaslProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSaslProto.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSaslProto proto.InternalMessageInfo

func (m *RpcSaslProto) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *RpcSaslProto) GetState() RpcSaslProto_SaslState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return RpcSaslProto_SUCCESS
}

func (m *RpcSaslProto) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *RpcSaslProto) GetAuths() []*RpcSaslProto_SaslAuth {
	if m != nil {
		return m.Auths
	}
	return nil
}

type RpcSaslProto_SaslAuth struct {
	Method               *string  `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	Mechanism            *string  `protobuf:"bytes,2,req,name=mechanism" json:"mechanism,omitempty"`
	Protocol             *string  `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	ServerId             *string  `protobuf:"bytes,4,opt,name=serverId" json:"serverId,omitempty"`
	Challenge            []byte   `protobuf:"bytes,5,opt,name=challenge" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcSaslProto_SaslAuth) Reset()         { *m = RpcSaslProto_SaslAuth{} }
func (m *RpcSaslProto_SaslAuth) String() string { return proto.CompactTextString(m) }
func (*RpcSaslProto_SaslAuth) ProtoMessage()    {}
func (*RpcSaslProto_SaslAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d427e17b4d03fb0, []int{4, 0}
}

func (m *RpcSaslProto_SaslAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSaslProto_SaslAuth.Unmarshal(m, b)
}
func (m *RpcSaslProto_SaslAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSaslProto_SaslAuth.Marshal(b, m, deterministic)
}
func (m *RpcSaslProto_SaslAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSaslProto_SaslAuth.Merge(m, src)
}
func (m *RpcSaslProto_SaslAuth) XXX_Size() int {
	return xxx_messageInfo_RpcSaslProto_SaslAuth.Size(m)
}
func (m *RpcSaslProto_SaslAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSaslProto_SaslAuth.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSaslProto_SaslAuth proto.InternalMessageInfo

func (m *RpcSaslProto_SaslAuth) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *RpcSaslProto_SaslAuth) GetMechanism() string {
	if m != nil && m.Mechanism != nil {
		return *m.Mechanism
	}
	return ""
}

func (m *RpcSaslProto_SaslAuth) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *RpcSaslProto_SaslAuth) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *RpcSaslProto_SaslAuth) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func init() {
	proto.RegisterEnum("hadoop.common.RpcKindProto", RpcKindProto_name, RpcKindProto_value)
	proto.RegisterEnum("hadoop.common.RpcRequestHeaderProto_OperationProto", RpcRequestHeaderProto_OperationProto_name, RpcRequestHeaderProto_OperationProto_value)
	proto.RegisterEnum("hadoop.common.RpcResponseHeaderProto_RpcStatusProto", RpcResponseHeaderProto_RpcStatusProto_name, RpcResponseHeaderProto_RpcStatusProto_value)
	proto.RegisterEnum("hadoop.common.RpcResponseHeaderProto_RpcErrorCodeProto", RpcResponseHeaderProto_RpcErrorCodeProto_name, RpcResponseHeaderProto_RpcErrorCodeProto_value)
	proto.RegisterEnum("hadoop.common.RpcSaslProto_SaslState", RpcSaslProto_SaslState_name, RpcSaslProto_SaslState_value)
	proto.RegisterType((*RPCTraceInfoProto)(nil), "hadoop.common.RPCTraceInfoProto")
	proto.RegisterType((*RPCCallerContextProto)(nil), "hadoop.common.RPCCallerContextProto")
	proto.RegisterType((*RpcRequestHeaderProto)(nil), "hadoop.common.RpcRequestHeaderProto")
	proto.RegisterType((*RpcResponseHeaderProto)(nil), "hadoop.common.RpcResponseHeaderProto")
	proto.RegisterType((*RpcSaslProto)(nil), "hadoop.common.RpcSaslProto")
	proto.RegisterType((*RpcSaslProto_SaslAuth)(nil), "hadoop.common.RpcSaslProto.SaslAuth")
}

func init() { proto.RegisterFile("RpcHeader.proto", fileDescriptor_5d427e17b4d03fb0) }

var fileDescriptor_5d427e17b4d03fb0 = []byte{
	// 1052 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x6f, 0x6f, 0xdb, 0x44,
	0x18, 0x9f, 0x9d, 0xa4, 0x4d, 0x9e, 0x26, 0x99, 0x73, 0x5b, 0x3b, 0xab, 0x9d, 0xb6, 0x28, 0x80,
	0x14, 0x21, 0x11, 0x41, 0x37, 0x84, 0x34, 0x24, 0x24, 0xd7, 0xb9, 0x36, 0xb7, 0xba, 0xb6, 0x39,
	0x3b, 0xad, 0x98, 0x40, 0x91, 0x71, 0x6e, 0x4d, 0x44, 0x62, 0x1b, 0xdb, 0x99, 0xc6, 0x17, 0xe1,
	0x35, 0x9f, 0x80, 0x0f, 0xc2, 0xb7, 0xe0, 0x4b, 0xf0, 0x1a, 0xdd, 0x5d, 0xec, 0x34, 0x4d, 0x91,
	0x78, 0xe7, 0xe7, 0xdf, 0xef, 0x9e, 0x3f, 0xbf, 0xe7, 0xce, 0xf0, 0x98, 0x26, 0xe1, 0x88, 0x05,
	0x53, 0x96, 0x0e, 0x92, 0x34, 0xce, 0x63, 0xd4, 0x9a, 0x05, 0xd3, 0x38, 0x4e, 0x06, 0x61, 0xbc,
	0x5c, 0xc6, 0x51, 0x8f, 0x40, 0x87, 0xba, 0xa6, 0x9f, 0x06, 0x21, 0x23, 0xd1, 0xfb, 0xd8, 0x15,
	0x3e, 0x3a, 0xec, 0xe7, 0x42, 0x33, 0xd5, 0x95, 0xae, 0xd2, 0xaf, 0xd0, 0x42, 0x44, 0xc7, 0x50,
	0x4f, 0x82, 0x94, 0x45, 0x39, 0x99, 0xea, 0xaa, 0x30, 0x95, 0x72, 0xcf, 0x81, 0x43, 0xea, 0x9a,
	0x66, 0xb0, 0x58, 0xb0, 0xd4, 0x8c, 0xa3, 0x9c, 0x7d, 0xcc, 0x4b, 0xb8, 0x50, 0xca, 0xba, 0xd2,
	0x55, 0xfb, 0x0d, 0x5a, 0x88, 0xe8, 0x39, 0x34, 0xb2, 0xf9, 0x6d, 0x14, 0xe4, 0xab, 0x94, 0x09,
	0xbc, 0x26, 0xdd, 0x28, 0x7a, 0xff, 0x54, 0xe0, 0x90, 0x26, 0x21, 0x65, 0xbf, 0xae, 0x58, 0x96,
	0xcb, 0x2a, 0x24, 0xe2, 0xd7, 0xb0, 0x9f, 0x26, 0xe1, 0xe5, 0x3c, 0x92, 0x09, 0xb6, 0x4f, 0x4f,
	0x06, 0x5b, 0x65, 0x0d, 0xa8, 0xb4, 0x0a, 0x6f, 0x5a, 0xf8, 0x22, 0x02, 0xb5, 0x34, 0x09, 0x9d,
	0x44, 0x1c, 0xd5, 0x3e, 0x7d, 0xb5, 0x1b, 0xb4, 0x7b, 0xd6, 0xc0, 0x49, 0x58, 0x1a, 0xe4, 0xf3,
	0x38, 0x92, 0x60, 0x12, 0x01, 0x1d, 0xc1, 0x5e, 0x18, 0x2c, 0x16, 0x64, 0xaa, 0x57, 0xba, 0x6a,
	0xbf, 0x43, 0xd7, 0x12, 0x6f, 0x50, 0xb8, 0x98, 0xcb, 0x06, 0x55, 0xbb, 0x6a, 0xbf, 0x49, 0x4b,
	0x19, 0xf5, 0x00, 0x52, 0x96, 0xa7, 0xbf, 0x99, 0xf1, 0x2a, 0xca, 0xf5, 0x5a, 0x57, 0xe9, 0x77,
	0xde, 0xa8, 0x5f, 0x7c, 0x45, 0xef, 0x68, 0xd1, 0x77, 0xd0, 0xc8, 0x8b, 0x61, 0xe8, 0x7b, 0x5d,
	0xa5, 0x7f, 0x70, 0xda, 0xbd, 0x9f, 0xe6, 0xfd, 0x79, 0xd1, 0x4d, 0x08, 0x7a, 0x0b, 0xad, 0xf0,
	0xee, 0x04, 0xf4, 0x7d, 0x81, 0xf1, 0xe9, 0x2e, 0xc6, 0xee, 0xa0, 0xe8, 0x76, 0x28, 0x9f, 0x5b,
	0x96, 0x07, 0x39, 0xa7, 0x41, 0x5d, 0xd2, 0x60, 0x2d, 0xf6, 0x7e, 0x82, 0xf6, 0x76, 0x5b, 0xd0,
	0x53, 0xd0, 0xa8, 0x6b, 0x4e, 0xce, 0x89, 0x6d, 0x58, 0x13, 0xd7, 0x30, 0x2f, 0xb1, 0xaf, 0x3d,
	0x42, 0x27, 0xf0, 0x8c, 0x6b, 0x4d, 0xc7, 0xf6, 0x89, 0x3d, 0x36, 0x7c, 0xe2, 0xd8, 0x85, 0x51,
	0x41, 0x3a, 0x3c, 0x15, 0x46, 0xcb, 0xf1, 0x30, 0x77, 0xb1, 0xb1, 0xc9, 0x1d, 0x34, 0xb5, 0xf7,
	0xd7, 0x1e, 0x1c, 0x89, 0x61, 0x64, 0x49, 0x1c, 0x65, 0xec, 0xee, 0xe4, 0x37, 0x7d, 0xe7, 0x54,
	0x6a, 0x95, 0x7d, 0xb7, 0x60, 0x8f, 0x27, 0xb7, 0xca, 0x74, 0xb5, 0xab, 0xf6, 0xdb, 0xa7, 0xaf,
	0x1f, 0x9a, 0xed, 0x0e, 0x1c, 0x57, 0x7b, 0x22, 0x4c, 0x36, 0x60, 0x8d, 0x81, 0xbe, 0x84, 0x27,
	0x19, 0x4b, 0x3f, 0xb0, 0x94, 0x24, 0xe1, 0x35, 0x4b, 0xb3, 0x79, 0x1c, 0xd9, 0xab, 0xa5, 0x5e,
	0xe9, 0x2a, 0xfd, 0x16, 0x7d, 0xc8, 0x84, 0x06, 0x80, 0xd8, 0xc7, 0x90, 0x25, 0xbc, 0x23, 0xe6,
	0x22, 0xc8, 0x32, 0x3b, 0x58, 0x32, 0xbd, 0xda, 0x55, 0xfa, 0x0d, 0xfa, 0x80, 0x85, 0xf3, 0x84,
	0xa5, 0x69, 0x9c, 0x5e, 0x65, 0xb7, 0x82, 0x09, 0x0d, 0x5a, 0xca, 0xe8, 0x07, 0x38, 0x10, 0xdf,
	0x43, 0x96, 0x07, 0xf3, 0x85, 0x60, 0x41, 0xfb, 0xf4, 0x9b, 0xff, 0x5d, 0x10, 0xe6, 0xb1, 0x66,
	0x3c, 0x65, 0xb2, 0xa6, 0xbb, 0x58, 0x5b, 0xf4, 0xdc, 0x17, 0xfb, 0xf6, 0x5f, 0xf4, 0xac, 0x3f,
	0x48, 0xcf, 0x3b, 0x94, 0x68, 0x6c, 0x53, 0xe2, 0x15, 0xb4, 0xb7, 0x9b, 0x89, 0x0e, 0x60, 0xdf,
	0x1b, 0x9b, 0x26, 0xf6, 0x3c, 0xed, 0x11, 0x6a, 0x40, 0x0d, 0x53, 0xea, 0x50, 0x4d, 0xe1, 0x9f,
	0xe7, 0x86, 0x6f, 0x58, 0x9a, 0xda, 0xfb, 0x5b, 0x85, 0xce, 0x4e, 0xc6, 0xe8, 0x10, 0x3a, 0xc2,
	0x77, 0x62, 0xb8, 0xae, 0x45, 0x4c, 0x41, 0x1b, 0xc9, 0x17, 0xa9, 0xb6, 0x9d, 0x89, 0x37, 0x36,
	0x47, 0x93, 0x2b, 0xec, 0x8f, 0x9c, 0xa1, 0xa6, 0xa2, 0x63, 0x38, 0xda, 0xb6, 0xb8, 0xd4, 0xf1,
	0x1d, 0xd3, 0xb1, 0xb4, 0x0a, 0x27, 0xa6, 0xb4, 0x71, 0xae, 0x79, 0x98, 0x5e, 0x63, 0xaa, 0x55,
	0xd1, 0x0b, 0x38, 0x96, 0x5a, 0x0f, 0x53, 0x62, 0x58, 0xe4, 0x1d, 0xb1, 0x2f, 0x26, 0x14, 0x7b,
	0xae, 0x63, 0x7b, 0x58, 0xab, 0x6d, 0xec, 0x3c, 0xea, 0x1a, 0x53, 0x8f, 0x33, 0xf7, 0x8a, 0x78,
	0x57, 0x86, 0x6f, 0x8e, 0xb4, 0x3d, 0xd4, 0x81, 0x96, 0xa8, 0x61, 0x32, 0xb6, 0x2f, 0x6d, 0xe7,
	0xc6, 0xd6, 0x00, 0x7d, 0x02, 0x2f, 0x0b, 0x95, 0x37, 0x76, 0x5d, 0x87, 0xfa, 0x78, 0x58, 0xc2,
	0xcb, 0x1a, 0x0e, 0xd0, 0x73, 0xd0, 0xa5, 0x13, 0xb1, 0xaf, 0x0d, 0x8b, 0x0c, 0x05, 0xfe, 0x08,
	0x1b, 0x43, 0x4c, 0xb5, 0x26, 0x7a, 0x09, 0x27, 0xd2, 0x3a, 0xc4, 0xdb, 0x79, 0x7d, 0x3f, 0xc6,
	0x9e, 0xaf, 0xb5, 0x78, 0xa1, 0xd2, 0x61, 0x27, 0xa5, 0x36, 0x3a, 0x02, 0x54, 0x9c, 0x6f, 0x8c,
	0xfd, 0x91, 0x43, 0xc9, 0x3b, 0x3c, 0xd4, 0x1e, 0xf7, 0xfe, 0xac, 0x40, 0x93, 0x4f, 0x26, 0xc8,
	0x16, 0xe5, 0x75, 0xfc, 0x41, 0x12, 0x57, 0x5c, 0x9e, 0x2d, 0x5a, 0x88, 0xe8, 0x5b, 0xa8, 0x89,
	0x71, 0xae, 0x77, 0xe8, 0xb3, 0x5d, 0xca, 0x95, 0x28, 0x03, 0xfe, 0xc5, 0xa7, 0xcd, 0xa8, 0x8c,
	0x41, 0x4f, 0xa1, 0x96, 0xc7, 0xbf, 0xb0, 0x48, 0x6c, 0x49, 0x93, 0x4a, 0x01, 0xbd, 0x81, 0x5a,
	0xb0, 0xca, 0x67, 0x99, 0x5e, 0xed, 0x56, 0x1e, 0xba, 0x87, 0xee, 0x43, 0x1a, 0xab, 0x7c, 0x46,
	0x65, 0xc8, 0xf1, 0xef, 0x0a, 0xd4, 0x0b, 0x1d, 0x5f, 0xfc, 0x25, 0xcb, 0x67, 0xf1, 0x74, 0xfd,
	0x86, 0xac, 0x25, 0xfe, 0x84, 0x2c, 0x59, 0x38, 0x0b, 0xa2, 0x79, 0xb6, 0x14, 0x79, 0x37, 0xe8,
	0x46, 0x21, 0xde, 0x2b, 0x8e, 0x1d, 0xc6, 0x0b, 0x91, 0x57, 0x83, 0x96, 0x32, 0xb7, 0xad, 0x37,
	0x79, 0xba, 0x5e, 0xd4, 0x52, 0xe6, 0xa8, 0xe1, 0x8c, 0x5f, 0x86, 0xd1, 0x2d, 0x13, 0xfb, 0xd9,
	0xa4, 0x1b, 0x45, 0xef, 0x47, 0x68, 0x94, 0xe5, 0x6f, 0xd3, 0xbc, 0x05, 0x0d, 0x1b, 0x5f, 0x38,
	0x3e, 0x31, 0x7c, 0xac, 0x29, 0xa8, 0x09, 0x75, 0x62, 0x13, 0x29, 0xa9, 0xdc, 0x68, 0x8e, 0x0c,
	0xcb, 0xc2, 0xf6, 0x05, 0xd6, 0x2a, 0xdc, 0x58, 0x32, 0xae, 0x8a, 0xea, 0x50, 0xbd, 0xa1, 0x86,
	0xab, 0xd5, 0x3e, 0x7f, 0x2b, 0xe6, 0x55, 0x3e, 0x5f, 0xe8, 0x31, 0x1c, 0x70, 0x96, 0x9c, 0x8d,
	0x89, 0xe5, 0x13, 0x5b, 0x7b, 0x84, 0x34, 0x68, 0x72, 0xc5, 0x0d, 0x25, 0xbe, 0x71, 0x66, 0xf1,
	0x73, 0x9e, 0xc1, 0x13, 0xae, 0x29, 0x68, 0x3f, 0x39, 0x1b, 0x9f, 0x9f, 0x63, 0xaa, 0xa9, 0x67,
	0xaf, 0xe1, 0x45, 0x9c, 0xde, 0x0e, 0x82, 0x24, 0x08, 0x67, 0xac, 0xe8, 0xfd, 0x3c, 0x09, 0xe5,
	0xcf, 0xc0, 0xcf, 0xab, 0xf7, 0x67, 0x9b, 0x1f, 0x04, 0x71, 0x5a, 0xf6, 0x87, 0xa2, 0xfc, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xe1, 0x2e, 0xb0, 0x19, 0x35, 0x08, 0x00, 0x00,
}
